extend class PB_WeaponBase
{

//////////////////////////// OVERLAYS ////////////////////////////////////////////////////////////////////////////////////
	action void A_LegOverlay(int layer, statelabel st)
	{
		invoker.WeaponScaleX = 1.0;
		A_Overlay(layer, st);
		invoker.WeaponScaleX = PB_PixelRenderingFix ? 1.2 : 1.0;
	}
	
	action void A_FlashOverlay(int layer = FLASH_LAYER, statelabel state = "MuzzleFlash")
	{
		A_Overlay(layer, state);
		A_OverlayFlags(layer, PSPF_RENDERSTYLE,true);
		A_OverlayRenderStyle(layer, STYLE_Add);
	}
	
	action void A_SetOverlaySprite(int layer, String str)
	{
		let psp = player.GetPSprite(layer);
		psp.sprite = GetSpriteIndex(str);
	}
  
	action void A_SetWeaponSprite(String str)
	{
		let psp = player.GetPSprite(PSP_WEAPON);
		//  let psp = player.GetPSprite(1);
		psp.sprite = GetSpriteIndex(str);
	}

	action void A_SetWeaponFrame(int frame)
	{
		let psp = player.GetPSprite(OverlayID());
		if(psp) psp.frame = frame;
	}

	action void A_SetWeaponSpriteEx(String str)
	{
		let psp = player.GetPSprite(OverlayID());
		if(psp) psp.sprite = GetSpriteIndex(str);
	}
		
	action void A_SetFlashWeaponSprite(String str)
	{
		let psp = player.GetPSprite(PSP_FLASH);
		psp.sprite = GetSpriteIndex(str);
	}

	action void A_SetSpawnSprite(String str)
	{
		sprite = GetSpriteIndex(str);
	}
	
	action void A_GunFlash2()
	{
		player.mo.PlayAttacking();
	}

//////////////////////////// WEAPON CASINGS ////////////////////////////////////////////////////////////////////////////////////
	action void PB_SpawnCasing(class<Actor> casing, double xOfs = 0, double horOfs = 0, double vertOfs = 0, double xSpeed = 0, double horSpeed = 0, double vertSpeed = 0, bool ejectionSmoke = true, bool sparks = false)
	{
		vertOfs -= (self.player.viewz - self.pos.z) / self.player.CrouchFactor;
        horOfs *= invoker.WeaponScaleX;
		double fovOfs = (120 - self.player.desiredfov) / 3.f; // good enough
		
		PlayerPawnBase plr = PlayerPawnBase(self);
		
		if(plr)
		{
			horOfs -= plr.FinalBob.x * 0.3;
			vertOfs -= plr.FinalBob.y * 0.3;
		}
	
		Vector3 spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (xOfs - (5.0 * abs(sin(self.pitch))) + fovOfs, horOfs, vertOfs), true);
		Vector3 svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed, horSpeed, vertSpeed));
	
		let pCase = Spawn(casing, spos);
		if(pCase)
		{
			pCase.vel = svel;
			pCase.angle = self.angle;
			pCase.target = self;	//so the casings dont collide with the shooter

			let pPBCase = PB_CasingBase(pCase);

            if(!pPBCase)
                return;

            if(!pPBCase.bNEVERSMOKE && ejectionSmoke) 
            {
                let pSmoke = PB_GunFireSmoke(Spawn('PB_CasingEjectionSmoke', spos));

                if(pSmoke) {
                    //svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed, horSpeed, vertSpeed));
                    vector3 unitVel = (xSpeed, horSpeed, vertSpeed).Unit();
                    pSmoke.master = self;
                    // svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed * 0.2, horSpeed * 0.2, vertSpeed * 0.2));
                    pSmoke.vel = svel;
                    pSmoke.pitch = -(90 - asin(unitVel.z)) * (unitVel.y);
                    //pSmoke.alpha = 0.25;
                    pSmoke.blowSpeed = 1.1;
                    pSmoke.fadeSpeed = 1.1;
                }
            }

            if(sparks)
            {
                vector3 randvel;
                int sparkcount = randompick(0, random(2, 4));
                for(int i = 0; i < sparkcount; i++)
                {
                    randvel = (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1));
                    spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (xOfs - (5.0 * abs(sin(self.pitch))) + fovOfs, horOfs, vertOfs) + randvel, true);
                    svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), (xSpeed, horSpeed, vertSpeed) + randvel);

                    let act = Spawn('PB_MuzzleSpark', spos);
                    act.vel = svel;
                    act.scale *= 0.35;
                    act.SetShade("FF9D2E");
                }
            }
		}
	}
	
	Action void PB_RevolverCasingSpawn(string AmmoSide)
	{
		int CasingCount;
		CasingCount = 6 - CountInv(AmmoSide);
		for(CasingCount > 0; CasingCount--;)
		{
			A_FireProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
		}
	}

//////////////////////////// SOUNDS ////////////////////////////////////////////////////////////////////////////////////
	uint16 sustainedFire;
	float lowAmmoVol;

	action void PB_GunShot(sound shotSound, sound mechSound, string tailInside, string tailOutside, string ammoType = "default", string ammoItem = "SuperMario64ForTheXboxOne", int ammoUse = 1)
	{
		PB_LowAmmoSoundWarning(ammoType, ammoItem, ammoUse);
		//console.printf("%f", 0.1 + (invoker.lowAmmoVol * 0.3));
		A_StartSound(shotSound, CHAN_WEAPON, volume: Clamp(PB_Math.LinearMap(invoker.sustainedFire, 3.0, 1.0, 0.5, 1.0), 0.5, 1.0));
		A_StartSound(mechSound, CHAN_AUTO, volume: 0.1 + (invoker.lowAmmoVol * 0.9), pitch: 0.3 + invoker.lowAmmoVol);
		PB_DynamicTail(tailInside, tailOutside);
	}

	const TAIL_EXT_CHECK_SAMPLES = 4;
	const TAIL_EXT_CHECK_ANGLE = 40;
	const TAIL_EXT_CHECK_STEPS = TAIL_EXT_CHECK_ANGLE / double(TAIL_EXT_CHECK_SAMPLES);
	
	action void PB_DynamicTail(string tailInside, string tailOutside)
	{	
		string tmpTailSound;
		uint intSamples;
		FLineTraceData ltrace;

		for(int i = 0; i < TAIL_EXT_CHECK_SAMPLES; i++)
		{
			LineTrace(angle, int.max, -90 + (i * TAIL_EXT_CHECK_STEPS), TRF_THRUHITSCAN | TRF_THRUACTORS, offsetz: player.ViewZ - pos.z, data: ltrace);
			// JGP_VisualTrace.DrawParticlesBetweenPoints((pos.xy, player.ViewZ), ltrace.HitLocation, 2, 60*TICRATE);

			if(ltrace.HitTexture)
			{
				if(ltrace.HitTexture != SkyFlatNum)
					intSamples++;
			}
		}

		double sndPitch = frandom(0.95, 1.05) * invoker.tailPitch;
		double intSndVolume = intSamples / float(TAIL_EXT_CHECK_SAMPLES);
		double extSndVolume = 1.0 - intSndVolume;
		double vol;

        double dist = Distance3D(players[consoleplayer].mo);
		
		for(int i = 0; i < 2; i++)
		{
			if(i == 1) { 
				if(extSndVolume <= 0.001 || !tailOutside)
					continue;

				tmpTailSound = "ext/"..tailOutside;
				vol = invoker.tailVolume * extSndVolume;
			}
			else {
				if(intSndVolume <= 0.001 || !tailInside)
					continue;

			 	tmpTailSound = "int/"..tailInside;
				vol = invoker.tailVolume * intSndVolume;
			}

            bool notPlayer = multiplayer && player != players[consoleplayer];

			A_StartSound("weapons/atmo/"..tmpTailSound, notPlayer ? 19 + (i * 4) : CHAN_AUTO, volume: vol * 0.5, pitch: sndPitch);

			// multiplayer thing
			if(notPlayer)
			{
                A_StartSound("weapons/atmo/dist/"..tmpTailSound, 20 + (i * 4), volume: vol, pitch: sndPitch);
                A_StartSound("weapons/atmo/far/"..tmpTailSound, 21 + (i * 4), volume: vol, pitch: sndPitch);
                A_StartSound("weapons/atmo/med/"..tmpTailSound, 22 + (i * 4), volume: vol, pitch: sndPitch);
			}
		}
	}

	action void PB_LowAmmoSoundWarning(string type = "default", string ammoItem = "SuperMario64ForTheXboxOne", int ammoUse = 1)
	{
		Ammo count;
		if(ammoItem == "SuperMario64ForTheXboxOne")
			count = invoker.ammo2;
		else
			count = Ammo(FindInventory(ammoItem));
			
		if(!count)
		{
			console.printf("PB_LowAmmoSoundWarning: Invalid ammo class");
			return;
		}
		
		int lowammocount = ceil(count.maxamount * 0.25);
		int currentammocount = count.amount;

		sound sndName = "weapons/lowammo/"..type;
		
		currentammocount /= ammoUse;
		lowammocount /= ammoUse;

		invoker.lowAmmoVol = 0.7;
		
		if(currentammocount <= lowammocount)
		{
			double clickvolume = clamp(PB_Math.LinearMap(currentammocount, 1.0, lowammocount, 1.0, 0.70), 0.7, 1.0);
			invoker.lowAmmoVol = clickvolume;
			A_StartSound(sndName, CHAN_AUTO, CHANF_OVERLAP, clickvolume, ATTN_STATIC, frandompick(0.98, 1.0));
			
			if(currentammocount == 1)
				A_StartSound("weapons/lowammo/sweetener", CHAN_AUTO, CHANF_OVERLAP, 1.0, ATTN_STATIC);
			
			//console.printf("%f %i %i", clickvolume, lowammocount, currentammocount);
			if(currentammocount == 0)
				console.printf("PB_LowAmmoSoundWarning: Ammo count is 0 instead of 1, was the function called after the ammo item was taken?");
		}
	}

//////////////////////////// MUZZLE SPARKS / FLASHES ////////////////////////////////////////////////////////////////////////////////////
    action void _SpawnMuzzleSparks(double d1, double d2, double d3, double angleOfs = 0, double size = 1.0, color col = 0xFF9D2E)
	{
        vector3 spos, svel, randvel;
        int sparkcount = randompick(0, random(5, 7));
        for(int i = 0; i < sparkcount; i++)
        {
            randvel = (frandom(0, 12), frandom(-5, 5), frandom(-5, 5));
            double fovOfs = (120 - self.player.desiredfov) / 3.f;
            spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle + angleOfs, self.pitch, self.roll), (self.radius + d2 - (5.0 * abs(sin(self.pitch))) + fovOfs, -d1, d3) + randvel, true);
		    svel = PB_Math.RelativeToGlobalCoords((0, 0, 0), (self.angle + angleOfs, self.pitch, self.roll), randvel + (7, 0, 0));

            let act = Spawn('PB_MuzzleSpark', spos);
            act.vel = svel;
            act.SetShade(col);
            act.scale *= size;
        }
	}

    action void _SpawnMuzzleSparksSG(double d1, double d2, double d3, double angleOfs = 0, double size = 1.0, color col = 0xFF9D2E)
	{
        vector3 spos, svel, randvel;
        int sparkcount = random(5, 7) * 3;
        FSpawnParticleParams PUFSPRK;
        PUFSPRK.Texture = TexMan.CheckForTexture("SPRKS0");
        PUFSPRK.Style = STYLE_Add;
        PUFSPRK.Flags = SPF_ROLL|SPF_FULLBRIGHT;
        PUFSPRK.FadeStep = -1;
        PUFSPRK.Color1 = "FFFFFF";
        for(int i = 0; i < sparkcount; i++)
        {
            randvel = (frandom(2, 10), frandom(-3, 3), frandom(-1, 1));
            double fovOfs = (120 - self.player.desiredfov) / 3.f;
            spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle + angleOfs, self.pitch, self.roll), (self.radius + d2 - (5.0 * abs(sin(self.pitch))) + fovOfs, -d1, d3) + (0, randvel.y, randvel.z), true);
		    svel = PB_Math.RelativeToGlobalCoords((0, 0, 0), (self.angle + angleOfs, self.pitch, self.roll), randvel);
            
            PUFSPRK.Vel = svel;
            PUFSPRK.Lifetime = random(3, 15);
            PUFSPRK.accel = (-PUFSPRK.vel / double(PUFSPRK.Lifetime)) + (0, 0, frandom(-0.1,-0.01));
            PUFSPRK.Startroll = random(0,359);
            PUFSPRK.RollVel = 0;
            PUFSPRK.StartAlpha = 1.0;
            
            PUFSPRK.Size = frandom(1, 2);
            //PUFSPRK.SizeStep = (-PUFSPRK.Size / double(PUFSPRK.Lifetime)) * 0.5;
            PUFSPRK.Pos = spos;
            Level.SpawnParticle(PUFSPRK);
        }
	}

    action void PB_MuzzleFlashEffects(double d1 = 0, double d2 = 0 , double d3 = 0, color col = 0xFF9D2E, bool sparks = false, bool light = true, int rad = 100, int tics = 2)
    {
        PlayerPawnBase plr = PlayerPawnBase(self);

        if(!plr) return;

        d3 -= 10.5;
		d2 += 15;

        _SpawnMuzzleSparks(d1, d2, d3, 0, 1.0, col);

        if(!light) return;
        plr.A_AttachLight('MuzzleFlashLight', DynamicLight.PointLight, col, rad, 0, DynamicLight.LF_DONTLIGHTSELF | DynamicLight.LF_ATTENUATE, (0, 0, self.player.viewz - floorz), 0);
        plr.m_MuzzleFlashTimer = tics;
    }
	
//////////////////////////// GUN SMOKES ////////////////////////////////////////////////////////////////////////////////////
	uint8 barrelHeat, leftBarrelHeat;
	
	// Beef: yes, these are actually used for the gun smoke stuff and not the overheat system
	action void PB_IncrementHeat(int flAmount = 1, bool flLeft = false)
	{
		if(!flLeft)
		{
			if(invoker.barrelHeat < 200)
				invoker.barrelHeat += flAmount * 10;
		}
		else	
		{
			if(invoker.leftBarrelHeat < 200)
				invoker.leftBarrelHeat += flAmount * 10;
		}
	}

	action void PB_SetMuzzleSmokeColor(string col)
	{
		invoker.smokeColor = col;
	}

	action void PB_CoolDownBarrel(double posOfsx = 0, double posOfsy = 0, double posOfsz = 0, double velOfsx = 0, double velOfsy = 0, double velOfsz = 0, double scaleadjust = 1, double alphaadjust = 1, bool nodual = false)
	{
		if((posOfsx <= 0 || nodual) && invoker.barrelHeat < 1 || posOfsx > 0 && invoker.leftBarrelHeat < 1 && !nodual)
			return;

		if(posOfsx > 0)
			invoker.leftBarrelHeat--;
		else
			invoker.barrelHeat--;
		
        if(!invoker.smoketype && Player) {
			invoker.smoketype = CVar.GetCVar("pb_gunsmoketype", Player);
		}
        int tmpSmkTp = invoker.smoketype.GetInt();
		if(tmpSmkTp != 0) {
			if(tmpSmkTp == 1) {
				PB_GunSmoke_Basic(posOfsx, posOfsy, posOfsz, "PB_GunFireSmoke");
			}
			return;
		}
		
		if(level.MapTime % 3 == 0)
		{
			double endingScale = clamp(PB_Math.LinearMap((posOfsX <= 0 || nodual) ? invoker.barrelHeat : invoker.leftBarrelHeat, 0, 20.0, 0.5, 1.0), 0.5, 1.0);

			PB_GunSmokeSpawn(
				(posOfsx, posOfsy, posOfsz), 
				(velOfsx, velOfsy, velOfsz) + (1, frandom(-0.3, 0.3), frandom(-0.3, 0.3) * endingScale),
				"PB_BarrelHeatSmoke",
				0.15 * scaleadjust,
				0.7 * endingScale * alphaadjust,
				1.3,
				0.4
			);
		}
	}

	//- L, 0 C, + R
	// [gng] credits to Agent_Ash for the position calculation, modified by me to fix the pitch bug
	Action PB_GunFireSmoke PB_GunSmokeSpawn(vector3 ofs, vector3 vofs, string SActor = "PB_GunFireSmoke", double scalemul = 1.0, double alphamul = 1.0, double blowspeed = 1.02, double fadeSpeed = 1.0, bool rollSprite = true, double slowBlowSpeed = 1.0)
	{
		ofs.z -= 10.5;
		ofs.y += 15;
		double fovOfs = (120 - self.player.desiredfov) / 3.f; // good enough
		
		PlayerPawnBase plr = PlayerPawnBase(self);
		
		if(plr)
		{
			ofs.x -= plr.FinalBob.x * 0.3;
			ofs.z -= plr.FinalBob.y * 0.3;
		}
		
		Vector3 spos = PB_Math.RelativeToGlobalCoords((self.pos.xy, self.player.viewz), (self.angle, self.pitch, self.roll), (self.radius + ofs.y - (5.0 * abs(sin(self.pitch))) + fovOfs, -ofs.x, ofs.z), true);
		Vector3 svel = PB_Math.RelativeToGlobalCoords((self.vel.xy, 0), (self.angle, self.pitch, self.roll), vofs);
		
		PB_GunFireSmoke Smoke = PB_GunFireSmoke(Spawn(SActor, spos));
		
		If(Smoke)
		{
			Smoke.master = invoker.owner;
			Smoke.vel += svel;
			if(rollSprite) 
            {
                Smoke.A_SetRoll(random(0, 359));
                Smoke.bXFLIP = randompick(0, 1);
                Smoke.bYFLIP = randompick(0, 1);
            }
			Smoke.scale *= scalemul;
			Smoke.alpha *= alphamul;
			Smoke.blowSpeed = blowspeed;
			Smoke.fadeSpeed = fadeSpeed;
            Smoke.angle = angle;
            Smoke.pitch = pitch;
            Smoke.slowBlowSpeed = slowBlowSpeed;
			
			if(invoker.smokeColor != "FFFFFF")
			{
				Smoke.A_SetRenderStyle(Smoke.alpha, STYLE_STENCIL);
				Smoke.SetShade(invoker.smokeColor);
			}
		}

		return Smoke;
	}

	// NONE of these functions should be called more than twice
	// [gng] alias for old PB_GunSmoke format function arguments
	Action void PB_GunSmoke_Basic(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
		PB_GunSmokeSpawn(
			(d1, d2, d3),
			(0, 0, 0),
			SActor,
			0.7,
			1.0,
			1.2,
			1.2
		);
		NashGoreStatics.QueueSmoke();
	}

	Action bool PB_GunSmoke_Prologue(in out double d1, in out double d2, in out double d3, string SActor)
    {
        d1 *= invoker.WeaponScaleX;

        if(!invoker.smoketype)
		{
			if(Player) invoker.smoketype = CVar.GetCVar("pb_gunsmoketype", Player);
			else return false;
		}

        int tmpSmkTp = invoker.smoketype.GetInt();
		if(tmpSmkTp != 0)
		{
			if(tmpSmkTp == 1)
				PB_GunSmoke_Basic(d1, d2, d3, SActor);

			return false;
		}

        NashGoreStatics.ClearPlayerSmoke();

        PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke",		// actor
			8,		  // scale multiplier
			0.3,		  // alpha multiplier
			1.5,		  // blow speed
            1.8,
            true,
            0.8
		);

        return true;
    }

    Action void PB_GunSmoke(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
        if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;
		
		// initial puff of muzzle gas
		/*PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			SActor,		// actor
			0.95,		  // scale multiplier
			1.0,		  // alpha multiplier
			1.02,		  // blow speed
			1.0  		  // fade speed
		);*/
		
		PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke_Var1",		// actor
			1.2,		  // scale multiplier
			0.6,		  // alpha multiplier
			1.2,		  // blow speed
            3
		);

		/*PB_GunSmokeSpawn(
			(d1, d2 + 6, d3), // offsets
			(1, 0, 0), 	  // velocites
			SActor,		// actor
			2.2,		  // scale multiplier
			0.7,		  // alpha multiplier
			1.05		  // blow speed
		);*/

		PB_GunSmokeSpawn(
			(d1, d2, d3),
			(0, 0, 0),
			SActor,
			0.7,
			1.0,
			1.02,
			1.2
		);

		PB_GunSmokeSpawn(
			(d1, d2 + 20.1, d3),
			(0, 0, 0),
			SActor,
			1.7,
			0.7,
			1.02,
			1.2
		);

		PB_GunSmokeSpawn(
			(d1, d2 + 43.2, d3),
			(0, 0, 0),
			SActor,
			2.7,
			0.6,
			1.02,
			1.2
		);

		//shockwave

		vector2 smkPOfs;

		/*smkPOfs = (frandom(10, 20), frandom(-1, 1));
		PB_GunSmokeSpawn(
			(d1 - 20, d2, d3 - 5 - smkPOfs.y),
			(0, smkPOfs.x, -smkPOfs.y),
			SActor,
			2,
			0.4,
			1.5,
			0.9
		);

		PB_GunSmokeSpawn(
			(d1 + 20, d2, d3 - 5 + smkPOfs.y),
			(0, -smkPOfs.x, smkPOfs.y),
			SActor,
			2,
			0.4,
			1.5,
			0.9
		);*/

		smkPOfs = (frandom(6, 10), frandom(-2, 2));
		PB_GunSmokeSpawn(
			(d1 - smkPOfs.x, d2 + 5, d3 + smkPOfs.y),
			(0, smkPOfs.x * 0.25, -smkPOfs.y * 0.25),
			SActor,
			1.4,
			0.6,
			1.2,
			0.9
		);
	
		PB_GunSmokeSpawn(
			(d1 + smkPOfs.x, d2 + 5, d3 - smkPOfs.y),
			(0, -smkPOfs.x * 0.25, smkPOfs.y * 0.25),
			SActor,
			1.4,
			0.6,
			1.2,
			0.9
		);

		NashGoreStatics.QueueSmoke();
	}
	
	// 5 actors
	Action void PB_GunSmoke_Deagle(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
		if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;

        PB_GunSmoke(d1, d2, d3, SActor);

		PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke_Var3",		// actor
			7,		  // scale multiplier
			1,		  // alpha multiplier
			1.5,	// blow speed
            3	  
		);
	}

    Action void PB_GunSmoke_Sniper(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
    {
        if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;

        PB_GunSmoke(d1, d2, d3, SActor);

		PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke_Var3",		// actor
			9,		  // scale multiplier
			1.5,		  // alpha multiplier
			1.5,	// blow speed
            3.5,
            slowBlowSpeed: 0.9 
		);

        PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke_Var4",		// actor
			3,		  // scale multiplier
			0.6,		  // alpha multiplier
			1.1,	// blow speed
            fadeSpeed: 1.25,
            rollSprite: false
		);
    }

	// 4 actors
	Action void PB_GunSmoke_FlashHider(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
		if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;
		
		double spd = frandom(2, 7);
        actor tmpsmk;
		/*PB_GunSmokeSpawn(
			(d1 + 12, d2, d3),
			(0, -spd, -1),
			SActor,
			1.5,
			0.6,
			1.2,
			1.2
		);
		PB_GunSmokeSpawn(
			(d1 - 12, d2, d3),
			(0, spd, -1),
			SActor,
			1.5,
			0.6,
			1.2,
			1.2
		);*/

        // initial puff of muzzle gas

        double randScale, randBlowSpeed, randFadeSpeed;
        randScale = frandom(0.6, 1.0);
        randBlowSpeed = frandom(1.1, 1.3);
        randFadeSpeed = frandom(2, 3);

		tmpsmk = PB_GunSmokeSpawn(
			(d1 + 4, d2, d3), 
			(0, -spd*0.2, 0), 
			"PB_GunFireSmoke_FastCloud", 
			randScale, 
			1, 
			randBlowSpeed,
			randFadeSpeed, 
			false
		);
		if(tmpsmk) {
            tmpsmk.roll = 90;
            tmpsmk.scale.y *= 1.3 / randScale;
        }

		// initial puff of muzzle gas
		tmpsmk = PB_GunSmokeSpawn(
			(d1 - 4, d2, d3), 
			(0, spd*0.2, 0), 
			"PB_GunFireSmoke_FastCloud", 
			randScale, 
			1, 
			randBlowSpeed,
			randFadeSpeed, 
			false
		); 
		if(tmpsmk) {
            tmpsmk.roll = -90;
            tmpsmk.scale.y *= 1.3 / randScale;
        }

		NashGoreStatics.QueueSmoke();
	}

	// 7 actors
	Action void PB_GunSmoke_Compensator(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
		if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;
		
		// initial puff of muzzle gas
		/*PB_GunSmokeSpawn(
			(d1, d2 - 2, d3), // offsets
			(0, 0, -0.5), 	  // velocites
			SActor,		// actor
			2.2,		  // scale multiplier
			0.5,		  // alpha multiplier
			1.03		  // blow speed
		);*/
		PB_GunSmokeSpawn(
			(d1, d2 + 5, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke_Var1",		// actor
			1.2,		  // scale multiplier
			0.6,		  // alpha multiplier
			1.2,		  // blow speed
            3
		);

		double spd = frandom(2, 7);
        actor tmpsmk;
		tmpsmk = PB_GunSmokeSpawn(
			(d1 + 12, d2, d3),
			(0, -spd, -1),
			"PB_GunFireSmoke_Var1",
			frandom(1, 1.4),
			frandom(0.2, 0.8),
			1.5,
			6,
            rollsprite: false,
            slowBlowSpeed: 0.8
		);
        if(tmpsmk) {
            tmpsmk.roll = -90 + frandom(0, 10);
            tmpsmk.bXFLIP = false;
            tmpsmk.bYFLIP = randompick(0, 1);
        }

		tmpsmk = PB_GunSmokeSpawn(
			(d1 - 12, d2, d3),
			(0, spd, -1),
			"PB_GunFireSmoke_Var1",
			frandom(1, 1.4),
			frandom(0.2, 0.8),
			1.5,
			6,
            rollsprite: false,
            slowBlowSpeed: 0.8
		);
        if(tmpsmk) {
            tmpsmk.roll = 90 + frandom(0, -10);
            tmpsmk.bXFLIP = true;
            tmpsmk.bYFLIP = randompick(0, 1);
        }
		
		double randScale, randBlowSpeed, randFadeSpeed;
        randScale = frandom(0.6, 1.0);
        randBlowSpeed = frandom(1.1, 1.3);
        randFadeSpeed = frandom(2, 3);

		tmpsmk = PB_GunSmokeSpawn(
			(d1 + 4, d2, d3), 
			(0, -spd*0.2, 0), 
			"PB_GunFireSmoke_FastCloud", 
			randScale, 
			1, 
			randBlowSpeed,
			randFadeSpeed, 
			false
		);
		if(tmpsmk) {
            tmpsmk.roll = 90;
            tmpsmk.scale.y *= 1.3 / randScale;
        }

		// initial puff of muzzle gas
		tmpsmk = PB_GunSmokeSpawn(
			(d1 - 4, d2, d3), 
			(0, spd*0.2, 0), 
			"PB_GunFireSmoke_FastCloud", 
			randScale, 
			1, 
			randBlowSpeed,
			randFadeSpeed, 
			false
		); 
		if(tmpsmk) {
            tmpsmk.roll = -90;
            tmpsmk.scale.y *= 1.3 / randScale;
        }

		PB_GunSmokeSpawn(
			(d1, d2 + 9.1, d3),
			(1.12, 0, 0),
            SActor,
			1.6,
			0.8,
			1.012,
			1.02
		);

		PB_GunSmokeSpawn(
			(d1, d2 + 27.6, d3),
			(1.44, 0, -0.5),
			SActor,
			3.2,
			0.6,
			1.05,
			1.2
		);

		NashGoreStatics.QueueSmoke();
	}

	Action void PB_GunSmoke_CompensatorHDMR(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
		if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;
		
		// initial puff of muzzle gas 
		PB_GunSmokeSpawn(
			(d1, d2 + 6, d3), // offsets
			(1, 0, 0), 	  // velocites
			SActor,		// actor
			2.3,		  // scale multiplier
			0.9,		  // alpha multiplier
			1.03		  // blow speed
		);
		PB_GunSmokeSpawn(
			(d1, d2 + 24.6, d3),
			(1.50, 0, 0),
			SActor,
			2.2,
			0.8,
			1.044,
			1.03
		);

		PB_GunFireSmoke smkact;
		// initial puff of muzzle gas

        // TR
		smkact = PB_GunSmokeSpawn(
			(d1 + 2, d2, d3 + 2), 
			(0, 0, 0),
			"PB_GunFireSmoke_Var2", 
			0.8, 
			2.0, 
			1.015,
			1.2,
			rollsprite: false
		);
		smkact.roll = -45;
        smkact.scale.y *= 1.6;

		smkact = PB_GunSmokeSpawn(
			(d1 - 2, d2, d3 - 2), 
			(0, 0, 0), 
			"PB_GunFireSmoke_Var2", 
			0.8, 
			2.0, 
			1.015,
			1.2,
			rollsprite: false
		);   
		smkact.roll = 135;
        smkact.scale.y *= 1.6;

		// initial puff of muzzle gas
		smkact = PB_GunSmokeSpawn(
			(d1 - 2, d2, d3 + 2), 
			(0, 0, 0),
			"PB_GunFireSmoke_Var2", 
			0.8,  
			2.0, 
			1.015,
			1.2,
			rollsprite: false
		);
		smkact.roll = -135;
        smkact.scale.y *= 1.6;

		// initial puff of muzzle gas
		smkact = PB_GunSmokeSpawn(
			(d1 + 2, d2, d3 - 2), 
			(0, 0, 0),
			"PB_GunFireSmoke_Var2",
			0.8,   
			2.0, 
			1.015,
			1.2,
			rollsprite: false
		); 
		smkact.roll = 45;
        smkact.scale.y *= 1.6;
		

		// initial puff of muzzle gas
		PB_GunSmokeSpawn(
			(d1 + frandom(-0.35, 0.35), d2 + 3.5, d3 + frandom(-0.2, 0.2)), 
			(1, 0, 0), 
			SActor, 
			1.2, 
			1.0, 
			1.02
		);

		NashGoreStatics.QueueSmoke();
	}

	Action void PB_GunSmoke_Launcher(double d1 = 0, double d2 = 0 , double d3 = 0, string SActor = "PB_GunFireSmoke")
	{
		if(!PB_GunSmoke_Prologue(d1, d2, d3, SActor)) return;
		
		PB_GunSmokeSpawn(
			(d1, d2 - 2, d3), // offsets
			(0, 0, -0.5), 	  // velocites
			SActor,		// actor
			2.2,		  // scale multiplier
			0.6,		  // alpha multiplier
			1.03		  // blow speed
		);

        PB_GunSmokeSpawn(
			(d1, d2, d3), // offsets
			(0, 0, 0), 	  // velocites
			"PB_GunFireSmoke_Var3",		// actor
			6,		  // scale multiplier
			1,		  // alpha multiplier
			1.3,	// blow speed
            2	  
		);

		PB_GunSmokeSpawn(
			(d1, d2 + 5.1, d3),
			(0, 0, 0),
			"PB_GunFireSmoke",
			1.7,
			1.0,
			1.02,
			1.2
		);

		PB_GunSmokeSpawn(
			(d1, d2 + 31.2, d3),
			(0, 0, 0),
			SActor,
			2.7,
			1.0,
			1.02,
			1.2
		);
	}
}