// This file contains the animations and functions used for the execution system
// Each monster has a function that decides which animation to play
// Those functions are then called by PB_ExecutionHandlerString()
// which is inside the execution system in PB_Execute()


extend class PB_WeaponBase
{
//////////////////////////// EXECUTION SYSTEM FUNCTIONS ////////////////////////////////////////////////////////////////////////////////////
	action void PB_Execute() 
	{
		if(CountInv("GrabbedBarrel") >= 1 || CountInv("GrabbedFlameBarrel") >= 1 || CountInv("GrabbedIceBarrel") >= 1) 
			return;
	
//		 CVar experimental_settings = CVar.FindCVar('pb_experimental');
		
// 		if(experimental_settings.GetBool()){
			//
		if(GetPointer(AAPTR_PLAYER_GETTARGET) != NULL)
		{
			
			if(GetPointer(AAPTR_PLAYER_GETTARGET).bCountKill)
			{
				LookExParams look;
				look.FOV = 360;
				
				Actor monster = GetPointer(AAPTR_PLAYER_GETTARGET);

				if (monster.IsVisible(self, true, look) && Distance3D(monster) < 200 ){
					
					int targetMaxHealth = monster.spawnHealth();
					int targetCurrentHealth = monster.health;
					
					if (actorCanBeExecuted(monster)) {
						
						// Move Monster and Player toward each other
						monster.A_Stop();
						double spd = 27.;
						vector3 delta = ( monster.pos.x - pos.x, monster.pos.y - pos.y, monster.pos.z - pos.z );
						double angleToMonster = AngleTo(monster);
						double pitchToMonster = VectorAngle( sqrt(delta.y * delta.y + delta.x * delta.x), delta.z );
						monster.A_SetPitch(pitchToMonster, SPF_INTERPOLATE);
						monster.A_SetAngle(angleToMonster+180,SPF_INTERPOLATE);
						
						vector3 neworigin = Vec3Offset(cos(angleToMonster) * spd,  sin(angleToMonster) * spd, sin(pitchToMonster) * spd);
						monster.SetOrigin(neworigin,true);
						
						// Set Player View and Properties
						int colorGreen = -16711936;
						int colorBlue = -16776961;
// 							A_LogInt(monster.BloodColor);
						if(monster.BloodColor == colorGreen)
						{
							PB_SetExecutionGreenBlood(true);
						}
						
						if(monster.BloodColor == colorBlue)
						{
							PB_SetExecutionBlueBlood(true);
						}
						
						A_SetAngle(AngleTo(monster));
						pitchToMonster = VectorAngle( sqrt(delta.y * delta.y + delta.x * delta.x), delta.z );
						A_SetPitch(-pitchToMonster);
						PB_SetPlayerExecutionProperties();
						
						StateLabel st = PB_ExecutionHandlerString(monster);
						monster.A_Die("Execution");
						A_Overlay(PSP_WEAPON,st);
						A_OverlayOffset(PSP_WEAPON,0,32);
						A_ClearOverlays(-998,-997);
					}
				}
			}
// 			}
		}
	}

	action StateLabel PB_ExecutionHandlerString(Actor monster) 
	{
	
		name enemy = monster.getClassName();
// 		A_print(enemy);
		
		switch(enemy){
			// Zombieman
			case 'PB_Zombieman':
				return PB_ExecuteZombieMan();
			case 'PB_PistolZombieman1':
				return PB_ExecuteZombieMan();
			case 'PB_HelmetZombieman':
				return PB_ExecuteZombieMan();
			case 'PB_PistolZombieman2':
				return PB_ExecuteZombieMan();
			
			// Imp
			case 'PB_Imp1':
				return PB_ExecuteImp();
				
			//Shotgun Guy
			case 'PB_ShotgunGuy':
				return PB_ExecuteShotguny();
				
			//Cacodemon
			case 'PB_Cacodemon':
				return PB_ExecuteCacodemon();
				
			default:
// 				A_Print("Execution Failed");
				return PB_ExecuteGeneric();
		}
	}

	action void PB_SetPlayerExecutionProperties() 
	{
		A_GiveInventory("ExecutionToken", 1); // When dashing, make sure to STOP player momentum, or else it fucks with the execution. Using a token for now.
		A_GiveInventory("PB_NoEffectInvul", 1); // So we don't break invulnerability
		PB_ClearDualWield();
		A_StopSound(CHAN_7);
		A_StopSound(CHAN_WEAPON);
		A_SetCrosshair(5);
		A_Stop();
		
		PlayerInfo plr = PlayerPawn(self).player;
// 		plr.mo.vel *= 0;
		//plr.cheats |= CF_TOTALLYFROZEN|CF_NOTARGET|CF_GODMODE|CF_DOUBLEFIRINGSPEED|CF_INSTANTWEAPSWITCH|CF_FRIGHTENING  ;
		plr.mo.bNODAMAGE = true;
		plr.mo.bNOPAIN = true;
//		SetPlayerProperty(0, 1, PROP_INVULNERABILITY); //This breaks the invulnerability power up. -JM
// 		A_GiveInventory("PB_NoEffectInvul",1); //Use PB_NoEffectInvul so that it doesn't break the REAL invulnerability -JM
// 		SetPlayerProperty(0, 1, PROP_TOTALLYFROZEN );
// 		SetPlayerProperty(0, 1, PROP_FLY);
		PB_SetExecutingEnemy(true);
	}
	
	action void PB_UnsetPlayerExecutionProperties() 
	{

		PlayerInfo plr = PlayerPawn(self).player;
		//plr.cheats &= ~(CF_TOTALLYFROZEN|CF_NOTARGET|CF_GODMODE|CF_INSTANTWEAPSWITCH|CF_DOUBLEFIRINGSPEED|CF_FRIGHTENING  );
		plr.mo.bNODAMAGE = false;
		plr.mo.bNOPAIN = false;
		PB_SetExecutingEnemy(false);
		PB_SetUsingMelee(false);
		PB_SetExecutionBlueBlood(false);
		PB_SetExecutionGreenBlood(false);
		//A_ClearTarget();
		A_TakeInventory("KnifeHasHit",1);
		A_TakeInventory("PB_NoEffectInvul",1);
		A_TakeInventory("HasCutingWeapon", 1);
		A_TakeInventory("ExecutionToken", 1);
		A_TakeInventory("PB_LockScreenTilt",1);
		A_SetRoll(0, SPF_INTERPOLATE);
		A_SetPitch(0, SPF_INTERPOLATE);
		A_ZoomFactor(1.0);
		A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, false);
		A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, false);
		
		
		//Determine how much health is returned (risk vs. reward)
		if (plr.health < 25) {
			A_GiveInventory("HealthBonus",20);
		}
		else if (plr.health < 50 && plr.health >= 25) {
			A_GiveInventory("HealthBonus",15);
		}
		else if (plr.health < 100 && plr.health >= 50) {
			A_GiveInventory("HealthBonus",10);
		}
		else if (plr.health < 200 && plr.health >= 100) {
			A_GiveInventory("HealthBonus",5);
		}
		else {
			A_GiveInventory("HealthBonus",1);
		}
	}
	
	action bool actorCanBeExecuted(Actor monster) 
	{	
		int targetMaxHealth = monster.spawnHealth();
		int targetCurrentHealth = monster.health;
		
		if(targetCurrentHealth < 1 || monster.bDORMANT)
			return false;
		 // In case the check desynced, found this during another gameplay
		
		if(CheckInventory("PB_PowerStrength",1) && (targetCurrentHealth <= targetMaxHealth*0.25 || targetCurrentHealth <= 150))
			return true;
	
		
		if(targetCurrentHealth < targetMaxHealth*0.20 || targetCurrentHealth <= 54)
			return true;
		
		return false;
		
	}

//////////////////////////// MONSTER EXECUTIONS FUNCTIONS ////////////////////////////////////////////////////////////////////////////////////
	action StateLabel PB_ExecuteGeneric() 
	{
		StateLabel result;
		int selector = (random(1,4));
		FLineTraceData RemoteRay;
		bool wallcheck = LineTrace(
			angle,
			120,
			pitch,
			TRF_THRUACTORS,
			offsetz: height-12,
			data: RemoteRay
		);
		
		result = "Execution_Generic";
		return result;
	}
	
	action StateLabel PB_ExecuteZombieMan() 
	{
		StateLabel result;
		int selector = (random(1,4));
		FLineTraceData RemoteRay;
		bool wallcheck = LineTrace(
			angle,
			120,
			pitch,
			TRF_THRUACTORS,
			offsetz: height-12,
			data: RemoteRay
		);
		
		// Drop Kick Fatality
		if((Pos.Z-floorz) > 8) {
			A_Warp(AAPTR_PLAYER_GETTARGET, 0, 0, 54, WARPF_USECALLERANGLE|WARPF_NOCHECKPOSITION);
			result = "Execution_Zombieman4";
			return result;
		}
		
		// Wall Kick Fatality
		if(wallcheck && RemoteRay.HitType == TRACE_HitWall) {
			result = "Execution_Zombieman3";
			return result;
		}
		
		// Generic Fatalities
		switch(selector){
			case 1:
				result = "Execution_Zombieman1";
				break;
			case 2:
				result = "Execution_Zombieman2";
				break;
			case 3:
				result = "Execution_Zombieman5";
				break;
			case 4:
				result = "Execution_Zombieman6";
				break;
		}
		return result;
	}
	
	// Cacodemon
	action StateLabel PB_ExecuteCacodemon() 
	{
		//A_GiveInventory("ExecutionToken", 1, AAPTR_PLAYER_GETTARGET); // Todo: Move this to a higher function once more fatalities are done
		StateLabel result;
		int selector = 1;//(random(1,2));
		
		// Generic Fatalities
		switch(selector){
			case 1:
				result = "Execution_Cacodemon1";
				break;
// 			case 2:
// 				result = "Execution_Imp2";
// 				break;
		}
		return result;
	}
	
	action StateLabel PB_ExecuteShotguny() 
	{
		//A_GiveInventory("ExecutionToken", 1, AAPTR_PLAYER_GETTARGET); // Todo: Move this to a higher function once more fatalities are done
		StateLabel result;
		int selector = (random(1,4));
		FLineTraceData RemoteRay;
		bool wallcheck = LineTrace(
			angle,
			120,
			pitch,
			TRF_THRUACTORS,
			offsetz: height-12,
			data: RemoteRay
		);
		
		// Drop Kick Fatality
		if((Pos.Z-floorz) > 8) {
			A_Warp(AAPTR_PLAYER_GETTARGET, 0, 0, 54, WARPF_USECALLERANGLE|WARPF_NOCHECKPOSITION);
			result = "Execution_ShotgunGuy4";
			return result;
		}
		
		// Wall Kick Fatality
		if(wallcheck && RemoteRay.HitType == TRACE_HitWall) {
			result = "Execution_ShotgunGuy3";
			return result;
		}
		
		// Generic Fatalities
		switch(selector){
			case 1:
				result = "Execution_ShotgunGuy1";
				break;
			case 2:
				result = "Execution_ShotgunGuy2";
				break;
			case 3:
				result = "Execution_ShotgunGuy5";
				break;
			case 4:
				result = "Execution_ShotgunGuy6";
				break;
		}
		return result;
	}
	
	
	action StateLabel PB_ExecuteImp() 
	{
		//A_GiveInventory("ExecutionToken", 1, AAPTR_PLAYER_GETTARGET); // Todo: Move this to a higher function once more fatalities are done
		StateLabel result;
		int selector = (random(1,2));
// 		int selector = 2;
		FLineTraceData RemoteRay;
		bool wallcheck = LineTrace(
			angle,
			120,
			pitch,
			TRF_THRUACTORS,
			offsetz: height-12,
			data: RemoteRay
		);
		
		// Drop Kick Fatality
		if((Pos.Z-floorz) > 8) {
			A_Warp(AAPTR_PLAYER_GETTARGET, 0, 0, 54, WARPF_USECALLERANGLE|WARPF_NOCHECKPOSITION);
			result = "Execution_Imp3";
			return result;
		}
		
		
// 		// Wall Kick Fatality
// 		if(wallcheck && RemoteRay.HitType == TRACE_HitWall) {
// 			result = "Execution_Zombieman3";
// 			return result;
// 		}
		
		// Generic Fatalities
		switch(selector)
		{
			case 1:
				result = "Execution_Imp1";
				break;
			case 2:
				result = "Execution_Imp2";
				break;
		}
		return result;
	}

//////////////////////////// EXECUTIONS HELPER FUNCTIONS ////////////////////////////////////////////////////////////////////////////////////
	action bool PB_executingEnemy()
	{
		return invoker.executingEnemy;
	}
	
	action void PB_SetExecutingEnemy(bool type)
	{
		invoker.executingEnemy = type;
	}
	
	action bool PB_GetExecutionBlueBlood()
	{
		return invoker.executionBlueBlood;
	}
	
	action void PB_SetExecutionBlueBlood(bool type)
	{
		invoker.executionBlueBlood = type;
	}
	
	action bool PB_GetExecutionGreenBlood()
	{
		return invoker.executionGreenBlood;
	}
	
	action void PB_SetExecutionGreenBlood(bool type)
	{
		invoker.executionGreenBlood = type;
	}

//////////////////////////// EXECUTION ANIMATIONS ////////////////////////////////////////////////////////////////////////////////////
	States
    {
	//Generic Execution (For placeholders)
		Execution_Generic:
			TNT1 A 0  {
				//A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.1);
			}	
			TNT1 A 0 A_Jump(256, "Generic1", "Generic2", "Generic3");
		
		Generic1:
			// Load blood variation sprites into virtual memory
			P2NK ABCDEFGHIJKLMNOPQRSTUV 0;
			P3NK ABCDEFGHIJKLMNOPQRSTUV 0;
			P4NK ABCDEFGHIJKLMNOPQRSTUV 0;
			P2NO ABCDEFGHIJKLMNOPQRSTUVW 0;
			P3NO ABCDEFGHIJKLMNOPQRSTUVW 0;
			P4NO ABCDEFGHIJKLMNOPQRSTUVW 0;
			
			P1NK ABCDEE 1 {  
				A_SetPitch(pitch-1.5);
				A_SetRoll(roll-5);
				A_SetAngle(angle-7.0);
			}
			TNT1 A 0 {
				A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
				A_ZoomFactor(1.15);
			}
			
			P1NK FG 1 {
				A_SetPitch(pitch+7.0);
				A_SetRoll(roll+9);
				A_SetAngle(angle+16.0);
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("execution/impact", CHAN_AUTO);
				A_ZoomFactor(1.25);
			}
			P2NK HIJKLMNO 1 {
				A_SetRoll(roll+10);
				A_SetAngle(angle+3);
				A_SetPitch(pitch+2);
				
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NK");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NK");}
				
					
			}
			
			P2NK PQRS 1 {
				A_SetRoll(roll-18);
				A_SetAngle(angle-2);
				A_SetPitch(pitch-4);
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NK");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NK");}
			}
			
			P2NK TU 1 {
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NK");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NK");}
			}
			P2NO ABCD 1 {
				A_SetRoll(roll+4);
				A_SetAngle(angle+0.5);
				A_SetPitch(pitch-2.0);
				
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NO");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NO");}
			}
			TNT1 A 0 {
				A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
				A_ZoomFactor(1.3);
			}
			P2NO EF 1 {
				A_SetRoll(roll-34);
				A_SetAngle(angle-15.0);
				A_SetPitch(pitch+5.0);
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NO");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NO");}
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("gore/heavyimpact", CHAN_AUTO);
				A_ZoomFactor(1.15);
			}
			//28
			P2NO GHIJKLMN 1 {
				A_SetRoll(roll+3);
				A_SetAngle(angle+5);
				A_SetPitch(pitch+2);
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NO");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NO");}
			}
			
			P2NO OPQ 1 {
				A_SetRoll(0, SPF_INTERPOLATE);
				A_SetAngle(angle+6);
				A_SetPitch(pitch-15);
				if(PB_GetExecutionBlueBlood()) {A_SetWeaponSprite("P3NO");}
				if(PB_GetExecutionGreenBlood()) {A_SetWeaponSprite("P4NO");}
			}
			
			TNT1 A 2;
			TNT1 A 1 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		Generic2:
			TNT1 AAA 1 {
				A_ZoomFactor(1.26);
				A_SetRoll(roll+20);
				A_SetAngle(angle+15);
				A_SetPitch(pitch+11);
			}
			TNT1 A 0 {
				A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			}
			P1NH DEF 1 {
				A_SetRoll(roll-25);
				A_SetAngle(angle-17);
				A_SetPitch(pitch-18);
			}
			P1NH G 1 {
				A_SetRoll(roll-6);
				A_SetAngle(angle-2);
				A_SetPitch(pitch-1);
				A_ZoomFactor(1.1);
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("execution/impact", CHAN_AUTO);
			}
			P1NH HIJKL 1 {
				A_ZoomFactor(1.0);
				A_SetRoll(roll+5);
				A_SetAngle(angle+9);
				A_SetPitch(pitch+8);
			}
			P1NH M 1;
			TNT1 A 4;
			TNT1 A 0 {
				A_Overlay(-9,"Generic2_Overlay");
				A_SetRoll(0,SPF_INTERPOLATE);
				A_StartSound("KICK", CHAN_AUTO );
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
			}
			TNT1 A 7;
			TNT1 A 2;
			TNT1 A 6;
			TNT1 A 3;
			TNT1 A 1 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		Generic2_Overlay:
			KIC5 AB 1 {
				A_SetRoll(roll+9);
				A_SetAngle(angle-9);
				A_SetPitch(pitch-2);
			}
			KIC5 CD 1 {
				A_SetRoll(roll+9);
				A_SetAngle(angle-8);
				A_SetPitch(pitch-2);
			}
			KIC5 DDD 1 {
				A_ZoomFactor(1.3);
				A_SetRoll(roll + 14);
				A_SetAngle(angle-14);
				A_SetPitch(pitch+8);
			}
			KIC5 EF 1 {
				A_SetRoll(roll+5);
				A_SetPitch(pitch-5);
				A_SetAngle(angle+4);
			}
			KIC5 G 1 {
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("execution/impact", CHAN_AUTO);
			}
			KIC5 H 1 A_ZoomFactor(1.1);
			KIC5 JKLM 1 {
				A_SetRoll(roll-10);
				A_SetAngle(angle+13);
				A_SetPitch(pitch-15);
				}
			Stop;
		Generic3:
			TNT1 AAA 1 {
				A_SetRoll(roll+12);
				A_SetAngle(angle+6);
				A_SetPitch(pitch+2);
				A_ZoomFactor(0.9);
			}
			TNT1 A 0 {
				A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			}
			P1NI DEFG 1 {
				A_SetRoll(roll-14);
				A_SetAngle(angle-9);
				A_SetPitch(pitch-3);
				A_ZoomFactor(0.8);
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("execution/impact", CHAN_AUTO);
			}
			P1NI HIJKL 1 {
				A_ZoomFactor(1.1);
				A_SetRoll(roll-10);
				A_SetAngle(angle-8);
				A_SetPitch(pitch+1);
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
			}
			P1NI M 1;
			TNT1 AAA 1 {
				A_SetRoll(roll+2);
				A_SetAngle(angle+1);
				A_SetPitch(pitch+1);
			}
			TNT1 A 0 {
				A_Overlay(-9,"Generic3_Overlay");
				A_SetRoll(0,SPF_INTERPOLATE);
				A_StartSound("KICK", CHAN_AUTO );
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
			}
			TNT1 A 7;
			TNT1 A 2;
			TNT1 A 6;
			TNT1 A 3;
			TNT1 A 1 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		Generic3_Overlay:
			KIC4 AB 1 {
				A_ZoomFactor(1.19);
				A_SetRoll(roll+18);
				A_SetAngle(angle+14);
				A_SetPitch(pitch+5);
			}
			KIC4 CD 1 {
				A_SetRoll(roll+12);
				A_SetAngle(angle+14);
				A_SetPitch(pitch+2);
			}
			KIC4 DDD 1 {
				A_SetRoll(roll-9);
				A_SetPitch(pitch+1);
			}
			KIC4 EF 1 {
				A_ZoomFactor(1.2);
				A_SetRoll(roll-5);
				A_SetPitch(pitch-6);
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
			}
			KIC4 G 1 {
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("execution/impact", CHAN_AUTO);
			}
			KIC4 H 1 A_ZoomFactor(1.15);
			KIC4 JKLM 1;
			Stop;
	//ZombieMan Executions
		Execution_Zombieman1_Overlay1:
			KIC5 ABCDEFGHIJKLM 1;
			Stop;
		Execution_Zombieman1:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Zombieman_Execution_1", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.1);
			}
			// Frame 1: 5 Ticks
			TNT1 A 0 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			P1N0 AB 1 {
				A_SetPitch(pitch-3, SPF_INTERPOLATE);
				A_SetRoll(roll+2, SPF_INTERPOLATE);
				A_SetAngle(angle-2);
			}
			P1N0 CD 1 { 
				A_SetRoll(roll+2, SPF_INTERPOLATE);
				A_SetAngle(angle-2);
			}
			P1N0 E 1 {
				A_SetRoll(roll-4, SPF_INTERPOLATE);
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("player/cyborg/fist", CHAN_AUTO);
				A_SetAngle(angle+9);
				A_SetPitch(pitch-2, SPF_INTERPOLATE);
			}
			// Frame 2: 12 Ticks
			P2NO FGHIJKLMOP 1 {
				A_SetRoll(roll-1,SPF_INTERPOLATE);
				A_SetAngle(angle+2);
				A_SetPitch(pitch+1, SPF_INTERPOLATE);
			}
			TNT1 A 0 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			P1NK FG 1 {
				A_SetRoll(roll+5,SPF_INTERPOLATE);
				A_SetPitch(pitch+2, SPF_INTERPOLATE);
				A_SetAngle(angle-5);
				A_SetPitch(pitch-15, SPF_INTERPOLATE);
			}
			// Frame 3: 15 Ticks
			TNT1 A 0 { 
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("misc/xdeath3", CHAN_AUTO);
				A_StartSound("player/cyborg/fist", CHAN_AUTO);
			}
			P2NK HIJKLMNOPQRSTUV 1 {
				A_SetRoll(roll+2);
				A_SetAngle(angle-5);
				A_SetPitch(pitch+2);
			}
			//Frame 4: 8
			TNT1 A 0 {
				A_Overlay(-9,"Execution_Zombieman1_Overlay1");
				A_SetRoll(0,SPF_INTERPOLATE);
				A_StartSound("KICK", CHAN_AUTO );
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
			}
			P6NA ABCDE 1 { 
				A_SetRoll(roll-1,SPF_INTERPOLATE);
				A_SetPitch(pitch+4);
				A_SetAngle(angle+10);
			}
			P6NA FGH 1 {
				A_SetPitch(pitch-10);
				A_SetRoll(roll-5);
				A_SetAngle(angle+4);
			}
			TNT1 A 0 { 
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("player/cyborg/fist", CHAN_AUTO);
			}
			P6NA IJKLM 1 A_SetRoll(roll+2,SPF_INTERPOLATE);
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;

		Execution_Zombieman2_Overlay1:
			//Frame 3: 6 ticks
			KIC2 ABCDEE 1;
			//Frame 4: 12 ticks
			KIC2 E 1 OffSet(-1,33);
			KIC2 E 1 OffSet(-2,34);
			KIC2 E 1 OffSet(-3,35);
			KIC2 E 1 OffSet(-4,36);
			KIC2 E 1 OffSet(-2,34);
			KIC2 E 1 OffSet(0,32);
			KIC2 E 1 OffSet(1,33);
			KIC2 E 1 OffSet(2,34);
			KIC2 E 1 OffSet(3,35);
			KIC2 E 1 OffSet(4,36);
			KIC2 E 1 OffSet(2,34);
			KIC2 E 1 OffSet(0,32);
			//Frame 5: 7 ticks
			KIC2 FGHIJKL 1;
			Stop;
		Execution_Zombieman2:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Zombieman_Execution_2", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.3);
			}
			//Frame 1: 5 ticks
			CL1M ABCDE 1 {
				A_SetPitch(pitch-3);
				A_SetRoll(roll+1);
			}
			TNT1 A 0 A_ZoomFactor(1.45);
			//Frame 2: 6 ticks
			CL1M FGFEFG 1 {
				A_SetPitch(pitch+4);
				A_SetRoll(roll-2);
			}
			TNT1 A 0 A_ZoomFactor(1.75, ZOOM_INSTANT);
			//Frame 3: 6 ticks
			TNT1 A 0 {
				A_Overlay(-9,"Execution_Zombieman2_Overlay1");
				A_StartSound("KICK", CHAN_AUTO );
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
			}
			CL1M HIJJJJ 1 {
				A_SetPitch(pitch+1, SPF_INTERPOLATE);
				A_SetRoll(roll-1,SPF_INTERPOLATE);
			}
			TNT1 A 0 {
				A_ZoomFactor(1.5, ZOOM_INSTANT);
				A_SetPitch(pitch-2, SPF_INTERPOLATE);
			}
			//Frame 4:  12 ticks
			TNT1 A 0 A_StartSound("gore/tension", CHAN_AUTO);
			CL1M J 1 OffSet(1,33) A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
			CL1M J 1 OffSet(2,34) A_ZoomFactor(1.64, ZOOM_INSTANT);
			CL1M J 1 OffSet(3,35) A_ZoomFactor(1.62, ZOOM_INSTANT);
			CL1M J 1 OffSet(4,36) A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
			CL1M J 1 OffSet(2,34) A_ZoomFactor(1.6, ZOOM_INSTANT);
			CL1M J 1 OffSet(0,32) A_ZoomFactor(1.58, ZOOM_INSTANT);
			CL1M J 1 OffSet(-1,33) A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
			CL1M J 1 OffSet(-2,34) A_ZoomFactor(1.56, ZOOM_INSTANT);
			CL1M J 1 OffSet(-3,35) A_ZoomFactor(1.54, ZOOM_INSTANT);
			CL1M J 1 OffSet(-4,36) A_FireProjectile("ShakeYourAss");
			1L1M J 1 OffSet(-2,34) A_ZoomFactor(1.5, ZOOM_INSTANT);
			1L1M J 1 OffSet(0,32) A_FireProjectile("ShakeYourAss");
			TNT1 A 0 A_ZoomFactor(1.2);
			//Frame 5: 
			TNT1 A 0 {
				A_StartSound("gore/break", CHAN_AUTO);
				A_SetRoll(roll+20);
			}
			1L1M KKLL 1 A_SetPitch(pitch-10, SPF_INTERPOLATE);
			TNT1 A 5 {
				A_SetPitch(pitch+15, SPF_INTERPOLATE);
				A_SetRoll(roll-12,SPF_INTERPOLATE);
			}
			TNT1 A 2 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;

		Execution_Zombieman3_Overlay1:
			KIC4 ABCDEFGHIIIIJKLM 1;
			Stop;
		Execution_Zombieman3:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Zombieman_Execution_3", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.35);
			}
			// Frame 1: 12 ticks
			TNT1 A 0 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			THRF ABCDEF 1 {
				A_SetRoll(roll-6);
				A_Setpitch(pitch+2);
				A_SetAngle(angle+4);
			}
			TNT1 A 6 {
				A_SetRoll(roll+36,SPF_INTERPOLATE);
				A_SetAngle(angle-24);
			}
			// Frame 2: 4 ticks
			TNT1 AA 2 A_Recoil(-2);
			TNT1 A 0 A_Stop;
			// Frame 3: 7 ticks
			TNT1 A 0 {
				A_Overlay(-9,"Execution_Zombieman3_Overlay1");
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
				A_StartSound("KICK", CHAN_AUTO );
				A_ZoomFactor(1.85, ZOOM_INSTANT);
			}
			P5NA ABCDEFG 1 {
				A_SetRoll(roll+10);
				A_SetAngle(angle-1);
			}
			TNT1 A 0 {
				A_ZoomFactor(2.2, ZOOM_INSTANT);
				A_FireProjectile("ShakeYourAss");
				A_SetPitch(pitch-2);
			}
			P5NA HH 1 {
				A_SetPitch(pitch-4);
				A_SetAngle(angle+3);
			}
			TNT1 A 0 A_ZoomFactor(1.48);
			// Frame 4: 7 ticks
			P5NA HIJKLMN 1 A_SetRoll(roll-10);
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;

		Execution_Zombieman4_Overlay1:
			CL1M CBA 1;
			Stop;
		Execution_Zombieman4_Overlay2:
			P5NA ABCDEFGHIJKLMN 1;
			Stop;
		Execution_Zombieman4:
			TNT1 A 0  {
				//A_SetAngle(angle-180);
				//A_Stop();
				A_SpawnItemEx("PB_Zombieman_Execution_4", 8, 4,-20,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(50, SPF_INTERPOLATE);
				A_ZoomFactor(2.25,ZOOM_INSTANT);
				A_StartSound("player/cyborg/fist", CHAN_AUTO);
				A_Overlay(9,"Execution_Zombieman4_Overlay1");
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
				A_FireProjectile("ShakeYourAss");
			}
			// Frame 1: 12 ticks
			SLDK ABCDE 1 {
				A_SetPitch(pitch+6);
				ThrustThingZ(0,25, 1,0);
				A_SetRoll(roll-4);
				A_SetAngle(angle-2);
			}
			SLDK FGHI 1 A_SetRoll(roll+5);
			// Frame 1: 8 ticks
			SLDK O 1 {
				A_StartSound("NECK_BRK", CHAN_AUTO );
				A_StartSound("BODYF", CHAN_AUTO );
				A_FireProjectile("ShakeYourAss");
			}
			SLDK P 1 {
				A_ZoomFactor(2.15);
				A_SetPitch(pitch-2, SPF_INTERPOLATE);
				A_SetAngle(angle-1);
			}
			SLDK Q 1 {
				A_SetPitch(pitch-2, SPF_INTERPOLATE);
				A_SetAngle(angle-1);
			}
			SLDK R 1 {
				A_ZoomFactor(2.0);
				A_SetPitch(pitch-2, SPF_INTERPOLATE);
				A_SetAngle(angle-1);
			}
			SLDK S 1 {
				A_SetPitch(pitch-2, SPF_INTERPOLATE);
				A_SetAngle(angle-1);
			}
			SLDK T 1 {
				A_ZoomFactor(1.8);
				A_SetPitch(pitch-4, SPF_INTERPOLATE);
			}
			SLDK U 1 A_SetPitch(pitch-4, SPF_INTERPOLATE);
			// 12
			TNT1 A 0 Offset(0,32);
			TNT1 A 5 {
				A_ZoomFactor(1.6);
			}
			TNT1 A 0 {
				A_ZoomFactor(1.86);
				A_Overlay(9,"Execution_Zombieman4_Overlay2");
				A_SetPitch(pitch-3);
			}
			KIC2 ABCDEFG 1 {
				A_SetRoll(roll-10);
				A_SetAngle(angle+3);
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss");
				A_SpawnItemEx("PB_ZombiemanHeadExplode", 15, 0, 25);
				A_SpawnItemEx("BigBloodSpot", 15, 0, 25);
			}
			KIC2 HHHHH 1 {
				A_SetPitch(pitch+2);
				A_SetAngle(angle-1);
			}
			//5
			KIC2 HIJKL 1 A_SetRoll(roll+5);
			TNT1 AAAAAAAA 1 A_SetPitch(pitch-10, SPF_INTERPOLATE);
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		Execution_Zombieman5:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Zombieman_Execution_5", 38, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.1);
			}
			// Frame 1: 5 Ticks
			TNT1 A 0 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			PBFT A 1 {
				A_ZoomFactor(1.25, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-5);
			}
			PBFT B 1 {
				A_ZoomFactor(1.35, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+2);
				A_SetRoll(roll-5);
			}
			PBFT C 1 {
				A_ZoomFactor(1.45, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+2);
				A_SetRoll(roll-5);
			}
			PBFT D 1 {
				A_ZoomFactor(1.55, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+3);
				A_SetRoll(roll-5);
			}
			PBFT E 1 {
				A_ZoomFactor(1.65, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle-8);
				A_SetRoll(roll-5);
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss");
				A_StartSound("NECK_BRK", CHAN_AUTO);
				A_StartSound("EYEPULL", CHAN_AUTO);
			}
			// Frame 2: 24 ticks
			TNT1 A 0 A_StartSound("gore/tension", CHAN_BODY);
			PBFT EFGH 1 {
				A_ZoomFactor(1.67, ZOOM_INSTANT);
				A_SetPitch(pitch-2);
				A_SetAngle(angle-1);
				A_SetRoll(roll+2);
			}
			PBFT EFGH 1 {
				A_ZoomFactor(1.68, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-2);
			}
			PBFT IJKL 1 {
				A_ZoomFactor(1.69, ZOOM_INSTANT);
				A_SetPitch(pitch-2);
				A_SetAngle(angle-1);
				A_SetRoll(roll+2);
				A_FireProjectile("ShakeYourAss");
			}
			PBFT MNOP 1 {
				A_ZoomFactor(1.70, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-2);
			}
			PBFT QRST 1 {
				A_ZoomFactor(1.71, ZOOM_INSTANT);
				A_SetPitch(pitch-2);
				A_SetAngle(angle-1);
				A_SetRoll(roll+2);
			}
			TNT1 A 0 A_StartSound("NeckSnap", CHAN_AUTO);
			PBFT UVWXY 1 {
				A_ZoomFactor(1.72, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-2);
			}
			PBFT Z 1 {
				A_FireProjectile("ShakeYourAss");
				A_ZoomFactor(1.8, ZOOM_INSTANT);
				A_StopSound(CHAN_BODY);
				A_StartSound("misc/gibbed", CHAN_AUTO);
			}
			PBF1 A 1 {
				A_SetPitch(pitch+6);
				A_SetAngle(angle-8);
				A_SetRoll(roll+10);
			}
			PBF1 BCD 1 {
				A_SetPitch(pitch+3);
				A_SetAngle(angle-2);
				A_SetRoll(roll+8);
			}
			TNT1 A 0 A_ZoomFactor(1.2);
			TNT1 AA 1 A_SetPitch(pitch+1);
			TNT1 AA 1;
			TNT1 AAAAA 1 {
				A_SetPitch(pitch-4);
				A_SetAngle(angle+1);
				A_SetRoll(roll-9);
			}
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		
		Execution_Zombieman6_Overlay1:
			KIC4 ABCDEFGHIJKLM 1;
			Stop;
		Execution_Zombieman6:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Zombieman_Execution_6", 41, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.2);
				A_Overlay(-9, "Execution_Zombieman6_Overlay1");
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
			}
			// 7
			P5NA ABCDEFG 1 {
				A_SetPitch(pitch+6);
				A_SetAngle(angle-1);
				A_SetRoll(roll+5);
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss");
				A_StartSound("NeckSnap", CHAN_AUTO);
			}
			// 14
			TNT1 A 5 A_Zoomfactor(1.3, ZOOM_INSTANT);
			TNT1 AAAAA 1 {
				A_SetAngle(angle+1);
				A_SetPitch(pitch-2);
				A_SetRoll(roll-7);
			}
			TNT1 A 0 {
				A_Zoomfactor(1.4, ZOOM_INSTANT);
				A_StartSound("weapons/fistwhoosh", CHAN_AUTO);
				A_SetRoll(roll-12);
			}
			G000 ABCD 1 {
				A_SetPitch(pitch-8);
				A_SetAngle(angle+3);
				A_SetRoll(roll-8);
			}
			TNT1 A 0 {
				A_Zoomfactor(1.6, ZOOM_INSTANT);
				A_FireProjectile("ShakeYourAss");
			}
			TNT1 A 0 {
				A_StartSound("gore/break", CHAN_AUTO);
				A_SetAngle(angle-6);
				A_SetPitch(pitch-6);
			}
			G000 EE 1 {
				A_SetPitch(pitch-10);
				A_SetAngle(angle-1);
				A_SetRoll(roll+9);
			}
			G000 F 1 {
				A_SetPitch(pitch-6);
				A_SetAngle(angle-1);
				A_SetRoll(roll+9);
				A_Zoomfactor(1.5, ZOOM_INSTANT);
			}
			G000 G 1 {
				A_SetPitch(pitch-4);
				A_SetAngle(angle-1);
				A_SetRoll(roll+9);
				A_Zoomfactor(1.44, ZOOM_INSTANT);
			}
			G000 H 1 {
				A_SetPitch(pitch-4);
				A_SetAngle(angle-1);
				A_SetRoll(roll+9);
				A_Zoomfactor(1.32, ZOOM_INSTANT);
			}
			G000 I 1 {
				A_SetPitch(pitch-4);
				A_SetRoll(roll+9);
				A_Zoomfactor(1.25, ZOOM_INSTANT);
			}
			G000 I 6 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		
		//Imp
		Execution_Imp1_Overlay1:
			P5NA ABCDEFG 1;
			Stop;
		Execution_Imp1:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Imp_Execution_1", 41, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.1, ZOOM_INSTANT);
				A_StartSound("KICK", CHAN_AUTO);
				A_Overlay(9,"Execution_Imp1_Overlay1");
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
			}
			// Frame 1: 5 Ticks
			AKCK ABCDE 1 {
				A_SetPitch(pitch-5.0);
				A_SetAngle(angle+2);
				A_SetRoll(roll-9.0);
			}
			// Frame 2: 14 Ticks
			AKCK E 1 Offset(-4,32);
			AKCK E 1 Offset(-8,32);
			AKCK E 1 Offset(-12,32) {
				A_SetPitch(pitch-12.0);
				A_SetAngle(angle+9.0);
				A_SetRoll(roll-19.0);
				A_FireProjectile("ShakeYourAss");
				A_StartSound("execution/impact", CHAN_AUTO);
				A_ZoomFactor(1.25, ZOOM_INSTANT);
			}
			AKCK E 1 Offset(-8,32) {
				A_SetPitch(pitch+6.0);
				A_SetAngle(angle-2.0);
				A_SetRoll(roll+5.0);
			}
			AKCK E 1 Offset(-4,32) {
				A_SetPitch(pitch+4.0);
				A_SetAngle(angle-2.0);
				A_SetRoll(roll+5.0);
			}
			AKCK E 1 Offset(0,32) {
				A_SetPitch(pitch+6.0);
				A_SetAngle(angle-4.0);
				A_SetRoll(roll+5.0);
				A_ZoomFactor(1.12, ZOOM_INSTANT);
			}
			AKCK DCBA 1 {
				A_SetPitch(pitch+7.0);
				A_SetAngle(angle-1);
				A_SetRoll(roll+1.0);
			}
			TNT1 AA 1 A_ZoomFactor(1.15, ZOOM_INSTANT);
			// Frame 3: 10 
			TNT1 A 0 {
				A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, false);
			}
			TNT1 AAA 1 {
				A_SetAngle(angle+11);
				A_SetPitch(pitch-12);
				A_SetRoll(roll-6.0);
			}
			TNT1 AAAA 1 {
				A_SetAngle(angle-3);
				A_SetPitch(pitch+2);
				A_SetRoll(roll+4.0);
			}
			P1NK EFG 1 {
				A_ZoomFactor(1.42, ZOOM_INSTANT);
				A_SetAngle(angle-6);
				A_SetPitch(pitch+3);
				A_SetRoll(roll+8.0);
			}
			// Frame 4
			P2NK H 1 {
				A_StartSound("execution/impactHeavy", CHAN_AUTO);
				A_SetPitch(pitch+4);
				A_SetAngle(angle-20);
				A_SetRoll(roll+25.0);
				A_FireProjectile("ShakeYourAss");
			}
			P2NK IJKLMNO 1 {
				A_SetPitch(pitch+3);
				A_SetAngle(angle-2);
				A_SetRoll(roll+5.0);
			}
			P2NK PQR 1 {
				A_ZoomFactor(1.15, ZOOM_INSTANT);
				A_SetPitch(pitch-6);
				A_SetAngle(angle+6);
				A_SetRoll(roll-15);
			}
			TNT1 A 5 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		Execution_Imp2:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Imp_Execution_2", 41, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.2, ZOOM_INSTANT);
				A_StartSound("KNIFUP", CHAN_AUTO);
			}
			TNT1 A 0 A_SetPitch(pitch+19);
			// Frame 1: 9 Ticks
			TNT1 AAA 1 {
				A_SetRoll(roll-75);
				A_SetPitch(pitch-4);
				A_SetAngle(angle+9);
			}
			TNT1 A 0 {
				A_ZoomFactor(1.4, ZOOM_INSTANT);
				A_StartSound("KNIFSWNG", CHAN_AUTO);
			}
			MC3S ABCDEF 1 {
				A_SetRoll(roll+6);
				A_SetPitch(pitch+1);
				A_SetAngle(angle-4);
			}
			// Frame 2: 4 Ticks
			TNT1 A 0 A_StartSound("Machete/Yum", CHAN_AUTO);
			MC3S GHIJ 1 {
				A_SetRoll(roll+6);
				A_SetPitch(pitch+2);
				A_SetAngle(angle-6);
			}
			TNT1 A 0 {
				A_ZoomFactor(1.15, ZOOM_INSTANT);
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
				A_StartSound("KICK", CHAN_AUTO);
			}
			// Frame 3: 12 Ticks
			KIC4 ABCDE 1 {
				A_SetRoll(roll-3);
				A_SetPitch(pitch-1);
				A_SetAngle(angle+2);
			}
			TNT1 A 0 A_ZoomFactor(1.05, ZOOM_INSTANT);
			KIC4 FFFF 1 {
				A_SetPitch(pitch-3);
				A_SetAngle(angle+4);
			}
			TNT1 A 0 A_ZoomFactor(1.5, ZOOM_INSTANT);
			KIC4 GHI 1 {
				A_SetRoll(roll+6);
				A_SetPitch(pitch-3);
				A_SetAngle(angle-3);
			}
			TNT1 A 0 {
				A_StartSound("gore/heavyimpact", CHAN_AUTO);
				A_FireProjectile("ShakeYourAss");
			}
			TNT1 A 0 A_ZoomFactor(1.1);
			KIC4 JKLM 1;
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;

		Execution_Imp3_Overlay1:
			G003 ABCDEFGHIJKLMNOP 1;
			Stop;
		Execution_Imp3_Overlay2:
			P6NA CDEFGGGG 1;
			Stop;
		Execution_Imp3:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Imp_Execution_3", 8, 4,-20,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(35);
				A_ZoomFactor(2.6,ZOOM_INSTANT);
				A_StartSound("player/cyborg/fist", CHAN_AUTO);
				A_Overlay(9,"Execution_Imp3_Overlay1");
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
				A_FireProjectile("ShakeYourAss");
			}
			// Frame 1: 12 ticks
			SLDK ABCDE 1 {
				A_SetPitch(pitch+6);
				ThrustThingZ(0,25, 1,0);
				A_SetRoll(roll-4);
				//A_SetAngle(angle+2);
			}
			SLDK FGHI 1 { 	
				A_SetRoll(roll+5);
				A_SetPitch(pitch+9);
			}
			// Frame 2: 8 ticks
			SLDK O 1 {
				A_ZoomFactor(2.5,ZOOM_INSTANT);
				A_StartSound("NECK_BRK", CHAN_AUTO );
				A_StartSound("BODYF", CHAN_AUTO );
				A_FireProjectile("ShakeYourAss");
			}
			SLDK P 1 {
				A_SetPitch(pitch-3);
				A_ZoomFactor(2.25, ZOOM_INSTANT);
				//A_SetAngle(angle-1);
			}
			SLDK Q 1 {
				A_SetPitch(pitch-3);
				//A_SetAngle(angle-1);
			}
			SLDK R 1 {
				A_SetPitch(pitch-4);
				A_ZoomFactor(2.10, ZOOM_INSTANT);
				//A_SetAngle(angle-1);
			}
			SLDK S 1 {
				A_SetPitch(pitch-4);
				//A_SetAngle(angle-1);
			}
			SLDK T 1 {
				A_SetPitch(pitch-5);
				A_ZoomFactor(1.8, ZOOM_INSTANT);
			}
			SLDK U 1 {
				A_SetPitch(pitch-5);
				A_ZoomFactor(1.6, ZOOM_INSTANT);
			}
			// Frame 3: 
			TNT1 A 0 Offset(0,32);
			TNT1 A 1 {
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
				A_ZoomFactor(1.86);
			}
			// Frame 3: 8
			PUNS JIH 1;
			TNT1 A 0 A_StartSound("weapons/fistwhoosh", CHAN_AUTO);
			P1NN ABC 1 {
				A_SetAngle(angle+3);
				A_SetPitch(pitch-2);
			}
			TNT1 A 0 A_StartSound("execution/impact", CHAN_AUTO);
			P2NN DE 1 {
				A_SetAngle(angle+2);
				A_SetPitch(pitch+4);
			}
			TNT1 AAAA 1 {
				A_SetAngle(angle-1);
				A_SetPitch(pitch-3);
			}
			// Frame 4: 6
			TNT1 A 0 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			P2NK ABCD 1 {
				A_SetAngle(angle-1);
				A_SetPitch(pitch-4);
				A_SetRoll(roll-2);
			}
			P2NK EF 1 {
				A_SetAngle(angle+4);
				A_SetPitch(pitch+6);
				A_SetRoll(roll-1);
			}
			TNT1 A 0 A_StartSound("execution/impact", CHAN_AUTO);
			// Frame 5: 13
			P2NK GHIJ 1 {
				A_SetAngle(angle-3);
				A_SetPitch(pitch+3);
				A_SetRoll(roll+4);
			}
			P2NK KLMNO 1 {
				A_SetAngle(angle-3);
				A_SetPitch(pitch+2);
				A_SetRoll(roll+2);
			}
			P2NK P 1 {
				A_SetAngle(angle+2);
				A_SetPitch(pitch-2);
				A_SetRoll(roll-9);
				A_Zoomfactor(1.7, ZOOM_INSTANT);
			}
			P2NK Q 1 {
				A_SetAngle(angle+2);
				A_SetPitch(pitch-2);
				A_SetRoll(roll-9);
				A_Zoomfactor(1.6, ZOOM_INSTANT);
			}
			P2NK R 1 {
				A_SetAngle(angle+2);
				A_SetPitch(pitch-2);
				A_SetRoll(roll-9);
				A_Zoomfactor(1.5, ZOOM_INSTANT);
			}
			P2NK S 1 {
				A_SetAngle(angle+2);
				A_SetPitch(pitch-2);
				A_SetRoll(roll-9);
				A_Zoomfactor(1.4, ZOOM_INSTANT);
			}
			TNT1 A 0 {
				A_Overlay(9,"Execution_Imp3_Overlay2");
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
			}
			// Frame 6: 13
			TNT1 A 0 {
				A_SetPitch(pitch-3);
				A_StartSound("KICK", CHAN_AUTO);
			}
			KIC1 A 1 {
				A_SetPitch(pitch-2);
				A_SetRoll(roll-1);
				A_Zoomfactor(1.35, ZOOM_INSTANT);
			}
			KIC1 B 1 {
				A_SetPitch(pitch-2);
				A_SetRoll(roll-1);
				A_Zoomfactor(1.3, ZOOM_INSTANT);
			}
			KIC1 C 1 {
				A_SetPitch(pitch-4);
				A_SetRoll(roll-2);
				A_Zoomfactor(1.25, ZOOM_INSTANT);
			}
			KIC1 D 1 {
				A_SetPitch(pitch-4);
				A_SetRoll(roll-2);
				A_Zoomfactor(1.2, ZOOM_INSTANT);
			}
			KIC1 EE 1 A_Zoomfactor(1.1, ZOOM_INSTANT);
			KIC1 E 1 {
				A_SetPitch(pitch+5);
				A_SetAngle(angle+3);
				A_SetRoll(roll-3);
				A_ZoomFactor(1.8);
			}
			KIC1 FG 1 {
				A_SetPitch(pitch+5);
				A_SetAngle(angle+3);
				A_SetRoll(roll-3);
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss");
				A_SpawnItemEx("BigBloodSpot", 15, 0, 25);
				A_StartSound("gore/heavyimpact", CHAN_AUTO);
			}
			KIC1 HHHHHHHH 1;
			TNT1 A 0 A_Zoomfactor(1.2);
			// Frame 7: 13
			KIC1 HIJKL 1 {
				A_SetPitch(pitch-1);
				A_SetRoll(roll+1);
			}
			TNT1 AAAAAAAA 1 A_SetPitch(pitch-10, SPF_INTERPOLATE);
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
		
		//Shotgunner
		Execution_ShotgunGuy1:
			TNT1 A 0  {
				A_SpawnItemEx("PB_ShotgunGuy_Execution_1", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.1);
			}
			Goto Execution_Zombieman1+2;
		Execution_ShotgunGuy2:
			TNT1 A 0  {
				A_SpawnItemEx("PB_ShotgunGuy_Execution_2", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.3);
			}
			Goto Execution_Zombieman2+2;
		Execution_ShotgunGuy3:
			TNT1 A 0  {
				A_SpawnItemEx("PB_ShotgunGuy_Execution_3", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.35);
			}
			Goto Execution_Zombieman3+2;
		Execution_ShotgunGuy4:
			TNT1 A 0  {
				A_SpawnItemEx("PB_ShotgunGuy_Execution_4", 8, 4,-20,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(50, SPF_INTERPOLATE);
				A_ZoomFactor(2.25,ZOOM_INSTANT);
				A_StartSound("player/cyborg/fist", CHAN_AUTO);
				A_Overlay(9,"Execution_Zombieman4_Overlay1");
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, true);
				A_FireProjectile("ShakeYourAss");
			}
			Goto Execution_Zombieman4+2;
		Execution_ShotgunGuy5:
			TNT1 A 0  {
				A_SpawnItemEx("PB_ShotgunGuy_Execution_5", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.35);
			}
			Goto Execution_Zombieman5+2;
		Execution_ShotgunGuy6:
			TNT1 A 0  {
				A_SpawnItemEx("PB_ShotgunGuy_Execution_6", 41, 0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETMASTER);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(1.2);
				A_Overlay(-9, "Execution_Zombieman6_Overlay1");
				A_OverlayFlags(-9,PSPF_PLAYERTRANSLATED, true);
			}
			Goto Execution_Zombieman6+2;
			
		//Cacodemon
		Execution_Cacodemon1:
			TNT1 A 0  {
				A_SpawnItemEx("PB_Cacodemon_Execution_1", 32, 0,0,0,0,0,0,SXF_NOCHECKPOSITION);
				A_SetPitch(0, SPF_INTERPOLATE);
				A_ZoomFactor(0.8);
			}
			// Frame 1: 5 Ticks
			TNT1 A 0 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			PBFT A 1 {
				A_ZoomFactor(1.25, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-5);
			}
			PBFT B 1 {
				A_ZoomFactor(1.35, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+2);
				A_SetRoll(roll-5);
			}
			PBFT C 1 {
				A_ZoomFactor(1.45, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+2);
				A_SetRoll(roll-5);
			}
			PBFT D 1 {
				A_ZoomFactor(1.55, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+3);
				A_SetRoll(roll-5);
			}
			PBFT E 1 {
				A_ZoomFactor(1.65, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle-8);
				A_SetRoll(roll-5);
			}
			TNT1 A 0 {
				A_FireProjectile("ShakeYourAss");
				A_StartSound("NECK_BRK", CHAN_AUTO);
				A_StartSound("EYEPULL", CHAN_AUTO);
			}
			// Frame 2: 24 ticks
			TNT1 A 0 A_StartSound("gore/tension", CHAN_BODY);
			G004 FFGH 1 {
				A_ZoomFactor(1.67, ZOOM_INSTANT);
				A_SetPitch(pitch-2);
				A_SetAngle(angle-1);
				A_SetRoll(roll+2);
			}
			G004 FFGH 1 {
				A_ZoomFactor(1.68, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-2);
			}
			G004 IJKL 1 {
				A_ZoomFactor(1.69, ZOOM_INSTANT);
				A_SetPitch(pitch-2);
				A_SetAngle(angle-1);
				A_SetRoll(roll+2);
				A_FireProjectile("ShakeYourAss");
			}
			G004 MNOP 1 {
				A_ZoomFactor(1.70, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-2);
			}
			G004 QRST 1 {
				A_ZoomFactor(1.71, ZOOM_INSTANT);
				A_SetPitch(pitch-2);
				A_SetAngle(angle-1);
				A_SetRoll(roll+2);
			}
			TNT1 A 0 A_StartSound("NeckSnap", CHAN_AUTO);
			G004 UVWXY 1 {
				A_ZoomFactor(1.72, ZOOM_INSTANT);
				A_SetPitch(pitch+2);
				A_SetAngle(angle+1);
				A_SetRoll(roll-2);
			}
			G004 Z 1 {
				A_FireProjectile("ShakeYourAss");
				A_ZoomFactor(1.8, ZOOM_INSTANT);
				A_StopSound(CHAN_BODY);
				A_StartSound("misc/gibbed", CHAN_AUTO);
			}
			G004 A 1 {
				A_SetPitch(pitch+6);
				A_SetAngle(angle-8);
				A_SetRoll(roll+10);
			}
			G004 BCD 1 {
				A_SetPitch(pitch+3);
				A_SetAngle(angle-2);
				A_SetRoll(roll+8);
			}
			TNT1 A 0 A_ZoomFactor(1.2);
			TNT1 AA 1 A_SetPitch(pitch+1);
			TNT1 AA 1;
			TNT1 AAAAA 1 {
				A_SetPitch(pitch-4);
				A_SetAngle(angle+1);
				A_SetRoll(roll-9);
			}
		
		
			TNT1 A 0 PB_UnsetPlayerExecutionProperties();
			TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
			Goto GoingToReady2;
    }
}
