class PB_RevLauncherFireCount : Inventory{Default{Inventory.MaxAmount 3;}}
extend class PB_WeaponBase
{
//////////////////////////// EQUIPMENT FUNCTIONS ////////////////////////////////////////////////////////////////////////////////////
	enum PB_Equipments
	{
		EQ_ERROR = -1,
		FRAG_GRENADE,
		PROX_MINE,
		STUN_GRENADE,
		LEECH,
		REV_GUN
	}

	int selectedEquipment;

	action void EQ_SetEquipment(int set)
	{
		invoker.selectedEquipment = set;
	}

	action int EQ_GetEquipment()
	{
		return invoker.selectedEquipment;
	}

	action state EQ_UseEquipmentLogic()
	{
		// Check token or if the player is dead
		if(findinventory("CantDoAction") || health <= 0)
			return resolveState("FailOverlay");

		// Setup
		A_ClearOverlays(-80,80);
		A_TakeInventory("RailgunInfrared", 1);
		A_StopSound(CHAN_WEAPON);
		A_StopSound(CHAN_VOICE);
		A_StopSound(CHAN_6);
		A_StopSound(CHAN_7);
		A_TakeInventory("UseEquipment", 1);
			
		// Get variables
		int mode = EQ_GetEquipment();
		
		bool grabbedBarrel;
		int barrelType;
		[grabbedBarrel,barrelType] 	= isHoldingBarrel();

		// Check barrels
		if(grabbedBarrel)
		{
			switch(barrelType)
			{
				case GRABBED_NORMAL_BARREL: return resolveState("IdleBarrel");
				case GRABBED_FLAME_BARREL: 	return resolveState("IdleFlameBarrel");
				case GRABBED_ICE_BARREL:	return resolveState("IdleIceBarrel");
			}
		}
		
		// Actual equipment logic
		switch(mode)
		{
			case FRAG_GRENADE: 	return resolveState("ThrowGrenade");
			case PROX_MINE: 	return resolveState("ThrowMine");
			case STUN_GRENADE: 	return resolveState("ThrowStun");
			case LEECH: 		return resolveState("ThrowLeech");
		}
		return resolveState(null);
	}

	action state EQ_SwitchEquipment()
	{
		A_TakeInventory("ToggleEquipment", 1);

		int mode 	= EQ_GetEquipment();
		int tokens 	= EQ_GetTokens();

		if(mode == tokens)
		{
			A_Print("$PB_ALREADYSELECTED");
			EQ_ClearGearboxTokens();
			return resolveState(null);
		}

		string showText;
		string playSound;
		switch(tokens)
		{
			case FRAG_GRENADE: 	showText = "$PB_SELECT_FRAG";	playSound = "GRNPIN";				break;	
			case PROX_MINE: 	showText = "$PB_SELECT_PROX";	playSound = "GRNPIN";				break;	
			case STUN_GRENADE:	showText = "$PB_SELECT_STUN";	playSound = "StunGrenadePickup";	break;	
			case LEECH: 		showText = "$PB_SELECT_LEECH";	playSound = "SiphonGrowl";			break;	
			case REV_GUN: 		showText = "$PB_SELECT_REVGUN";	playSound = "REVUP";				break;	
		}
		
		EQ_SetEquipment(tokens);
		A_Print(showText); 
		A_StartSound(playSound, 3);
		EQ_ClearGearboxTokens();

		return resolveState(null);
	}

	action void EQ_ClearGearboxTokens()
	{
		A_SetInventory("WW_FragGrenadeSelected",0);
		A_SetInventory("WW_ProximityMineSelected",0);
		A_SetInventory("WW_StunGrenadeSelected",0);
		A_SetInventory("WW_LeechSelected",0);
		A_SetInventory("WW_RevGunSelected",0);
	}
	
	// Convert the tokens into an int for easier use
	action int EQ_GetTokens()
	{
		if(FindInventory("WW_FragGrenadeSelected")) 
			return FRAG_GRENADE;
		else if(FindInventory("WW_ProximityMineSelected"))
			return PROX_MINE;
		else if(FindInventory("WW_StunGrenadeSelected"))
			return STUN_GRENADE;
		else if(FindInventory("WW_LeechSelected"))
			return LEECH;
		else if(FindInventory("WW_RevGunSelected"))
			return REV_GUN;
		else
			return EQ_ERROR; // If it returns this then something is catastrophically wrong lol
	}

//////////////////////////// STATES ////////////////////////////////////////////////////////////////////////////////////
	States
	{
		UseEquipment:
			TNT1 A 0 EQ_UseEquipmentLogic();
			//TNT1 A 0 A_JumpIfInventory("RevGunSelected", 1, "FireRevGun");
			//More stuff to come.....
			Goto GoingToReady;

		// Beef: These Two Functions are run in another layer, thats why they go to Equipment_Toggle_Handler_Overlay
		// we should really move the check from overlays to just DoEffect()
		WheelCancelEquipment:
			TNT1 A 0 {
				EQ_ClearGearboxTokens();
				A_SetInventory("CantWeaponSpecial",0);
			}
			goto Equipment_Toggle_Handler_Overlay;
		SwitchEquipment:	
			TNT1 A 0 EQ_SwitchEquipment();
			goto Equipment_Toggle_Handler_Overlay;

//////////////////////////// EQUIPMENT ANIMATIONS ////////////////////////////////////////////////////////////////////////////////////
		LeechBeam:
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			Loop;
		ThrowLeech:
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_Dtech", 4, 2);
			TNT1 A 0 A_Print("Insufficient Demon Energy");
			Goto GoingToReady;
			TNT1 A 0 PB_SetZoom(false);
			TNT1 A 1 A_StartSound("SiphonActive", 3);
			SYNP KLMNO 1 A_WeaponOffset(0,32);
			TNT1 A 0 {
				A_StopSound(3);
				A_Overlay(PSP_LEECHBEAMLAYER, "LeechBeam");
			}
		HoldLeech:
			SYNP ABCDEF 2 {
				A_StartSound("SiphonHold",3,CHANF_LOOPING);
				A_FireBullets(0, 0, -1, 3, "SiphonPuff", FBF_NORANDOM|FBF_NOFLASH);
				A_TakeInventory("PB_Dtech", 4, TIF_NOTAKEINFINITE);
			}
			TNT1 A 0 A_JumpIf(CountInv("PB_Dtech") > 4 && PressingUser1(), "HoldLeech");
			TNT1 A 0 {
				A_StopSound(3);
				A_ClearOverlays(PSP_LEECHBEAMLAYER,PSP_LEECHBEAMLAYER);
				if(CountInv("PB_Dtech") < 4 && PressingUser1()) {
					A_Print("Insufficient Demon Energy");
				}
			}
			SYNP ONMLK 1;
			TNT1 A 0 {
				A_WeaponOffset(0,32);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		ThrowStun:
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_StunGrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Stun Grenades Left");
			Goto GoingToReady;
			TNT1 A 0 PB_SetZoom(false);
			STNG BCDEF 1;
			STNG F 1 Offset(-2,34);
			TNT1 A 0 A_StartSound("StunGrenadeArm", 2);
			STNG GIJJJIHGKLMNOP 1;
			
			HND1 I 1 A_StartSound("THRGRN", 1);
			TNT1 A 0 A_TakeInventory("PB_StunGrenadeAmmo", 1, TIF_NOTAKEINFINITE);
			HND1 J 1 A_FireProjectile("PB_ThrownStunGrenade",0,0,0,0,0,0);
			HND1 KLMNOPQ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			FireRevGun:
				TNT1 A 0 A_TakeInventory("UseEquipment", 1);
				TNT1 A 0 A_JumpIfInventory("PB_QuickLauncherAmmo", 1, 2);
				TNT1 A 0 A_Print("No Quick Launcher Missiles Left");
				stop;
				TNT1 A 0 {A_StartSound("revup", CHAN_AUTO, CHANF_OVERLAP);}
				RVCA ABCDEFGHIJK 1;
				RVCF AB 1;
			FiringRevGun:
				TNT1 A 0 {if (player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))){return ResolveState("FireRevGunDeselect");} return ResolveState(null);}
				RVCF C 1 BRIGHT {
					A_AlertMonsters();
					A_TakeInventory("PB_QuickLauncherAmmo", 1, TIF_NOTAKEINFINITE);
					/*
					if(!FindInventory("PB_RevLauncherFireCount")){A_AlertMonsters();}
					if(CountInv("PB_RevLauncherFireCount")<3){A_GiveInventory("PB_RevLauncherFireCount",1);
					}else{A_TakeInventory("PB_QuickLauncherAmmo", 1);A_SetInventory("PB_RevLauncherFireCount",0);}
					*/
					A_FireProjectile("Alerter",0,0,-1,0);
					A_FireProjectile("DoomerRevenantSeeker3", random(4, -4), 0, -16, 8);
					A_StartSound("hellishmissle/fire",CHAN_AUTO, CHANF_OVERLAP, 0.5, pitch:frandom(0.95, 1.05));
					if(JustPressed(BT_USER1) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						SetInventory("UseEquipment",1);
					}
				}
				RVCF D 1 BRIGHT {
					A_StartSound("hellishmissle/fire", CHAN_AUTO, CHANF_OVERLAP, 0.5, pitch:frandom(0.95, 1.05));
					A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
					A_FireProjectile("DoomerRevenantSeeker2", random(4, -4), 0, 16, 8);
					if(JustPressed(BT_USER1) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						SetInventory("UseEquipment",1);
					}
				}
				RVCF EFG 1 BRIGHT {
					if(player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))) {
						return ResolveState("FireRevGunDeselect");
					}
					if((JustPressed(BT_USER1) || FindInventory("UseEquipment")) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						return ResolveState("FireRevGunFinish");
					}
					return ResolveState(null);
				}
				RVCF HI 1 {
					if(player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))) {
						return ResolveState("FireRevGunDeselect");
					}
					if((JustPressed(BT_USER1) || FindInventory("UseEquipment")) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						return ResolveState("FireRevGunFinish");
					}
					return ResolveState(null);
				}
				TNT1 A 0 A_JumpIf(CountInv("PB_QuickLauncherAmmo") > 0 && (PressingUser1() || CVar.GetCVar("pb_toggle_launchers", player).GetBool()), "FiringRevGun");
				goto FireRevGunFinish;
			FireRevGunFinish:
				TNT1 A 0 {
					if(CountInv("PB_QuickLauncherAmmo") < 1 && (PressingUser1() || CVar.GetCVar("pb_toggle_launchers", player).GetBool() && !FindInventory("UseEquipment"))) {
						A_Print("No Quick Launcher Missiles Left");
					}
					A_TakeInventory("UseEquipment", 1);
					A_TakeInventory("ToggleEquipment", 1);
				}
				RVCF BA 1;
				RVCA K 1 A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
				RVCA JIHGFEDCB 1;
				RVCA A 1 {
					A_TakeInventory("UseEquipment", 1);
					A_TakeInventory("ToggleEquipment", 1);
				}
				stop;
			FireRevGunDeselect:
				RVCA H 1 {
					A_TakeInventory("UseEquipment", 1);
					A_TakeInventory("ToggleEquipment", 1);
					A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
				}
				RVCA FDCB 1;
				stop;
		ThrowGrenade:
			TNT1 A 0 {
				A_StopSound(6);
				A_StopSound(CHAN_VOICE);
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_GrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Frag Grenades Left");
			Goto GoingToReady;
			TNT1 A 0 PB_SetZoom(false);
			TNT1 A 0 A_Giveinventory("PlayerIsThrowingAGrenade",1);
			HNDF ABCDE 1 A_SetRoll(roll+2.0, SPF_INTERPOLATE);
			HNDF FGHI 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_StartSound("OPNGRN",0);
			HNDF JKLMNOPQR 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_JumpIfInventory("UseEquipment", 1, "TossGrenade");
			TNT1 A 1 A_SetRoll(roll-18.0);
			HND1 I 1 A_StartSound("THRGRN",0);
			HND1 J 1 {
				A_FireProjectile("PB_ThrownGrenade",0,0,0,0,0,0);
				A_TakeInventory("PB_GrenadeAmmo", 1, TIF_NOTAKEINFINITE);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
			}
			HND1 KLMNOPQ 1 A_SetRoll(roll-5.0);
			TNT1 A 0 {
			A_SetRoll(0, SPF_INTERPOLATE);
			A_TakeInventory("UseEquipment", 1);
			A_TakeInventory("ToggleEquipment", 1);
			A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		TossGrenade:
			TNT1 A 1;
			HND1 RSTU 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_StartSound("THRGRN", 1);
				A_TakeInventory("PB_GrenadeAmmo", 1, TIF_NOTAKEINFINITE);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
				A_FireProjectile("ThrownGrenade15", 0,0,0,-2,0,3);
			}
			HND1 VWXY 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_SetRoll(0);
				A_TakeInventory("PB_LockScreenTilt",1);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		ThrowMine:
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_ProxMineAmmo", 1, 2);
			TNT1 A 0 A_Print("No Proximity Mines Left");
			Goto GoingToReady;
			TNT1 A 0 PB_SetZoom(false);
			XPFF FEDCBA 1;
			XPFS B 4 A_StartSound("weapons/pbarm", 2);
			XHFF A 0 {
				A_StartSound("MINE002", 3);
				A_ThrowGrenade("PB_ThrownProxMine",4,11,1,0);
				A_TakeInventory("PB_ProxMineAmmo", 1, TIF_NOTAKEINFINITE);
			}
			XHFF MNOPQRSTUVWXYZ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
	}
}