#include "./BaseWeapon_Functions.zsc"
#include "./BaseWeapon_Equipment.zsc"
#include "./BaseWeapon_Melee.zsc"
#include "./BaseWeapon_Executions.zsc"
#include "./BaseWeapon_Barrels.zsc"
#include "./BaseWeapon_FX.zsc"

class PB_WeaponBase : DoomWeapon
{
	Mixin PB_CheckFunctions;
	mixin PB_LocationalDamage;
	double exaggerationMultiplier;
	Actor laseractor;
	Actor InvActor;
	Vector3 invactorpos;
	
	string primaryFormat, secondaryFormat, leftFormat;
	int primaryDivisor, secondaryDivisor, leftDivisor;
	bool showPrimary, showSecondary, showLeft;
	property HUDFormatPrimary : showPrimary, primaryFormat, primaryDivisor;
	property HUDFormatSecondary : showSecondary, secondaryFormat, secondaryDivisor;
	property HUDFormatLeft : showLeft, leftFormat, leftDivisor;
	
	bool chamberEmpty;
	bool leftChamberEmpty;
	bool magEmpty;
	bool leftMagEmpty;
	bool magUnloaded;
	bool leftMagUnloaded;
	int integer;
	
	bool leftHandMelee;
	property leftHandMelee : leftHandMelee;
	
	int maxOverheat;
	property maxOverheat : maxOverheat;
	
	int overheatCoolingRate;
	property overheatCoolingRate : overheatCoolingRate;
	
	int overheat;
	int leftOverheat;
	
	string lastGrenadeType;
	bool respected;
	
	string rocketLauncherMode;
	bool akimboMode;
	
	bool FiringLeftWeapon;
	bool FiringRightWeapon;
	
	bool usingEquipment;
	bool usingMelee;
	bool usingKick;
	bool executingEnemy;
	bool executionBlueBlood;
	bool executionGreenBlood;
	double horizontalOffsetRecoil;
	property OffsetRecoilX: horizontalOffsetRecoil;

	double verticalOffsetRecoil;
	property OffsetRecoilY: verticalOffsetRecoil;
	
	bool alreadyRespected;

	bool stayInEmptyLayer;
	
	//Cemtex's PB_AmmoIntoMag function variables
	string AmmoMag;
	string AmmoPool;
	int MagazineMaxFill;
	int TakeGiveResrvAmnt; //So no states would be made for weapons that take more than one of their desired reserve ammo
	
	protected int BraceTicker;
	bool GunBraced;
	
	bool hasWheelSpecial;					//this tells the wheel handler a weapon actually uses the wheel, this also allows to set when a weapon can use the wheel (like upgraded/unupgraded dmr)
	class <wheelinfocontainer> wheelinfo;	//the object that holds the info about the wheel modes for this weapon
	
	property UsesWheel:hasWheelSpecial;
	property WheelInfo:wheelinfo;

	transient cvar smoketype;

	double tailVolume;
	property TailSoundVolume : tailVolume;

	double tailPitch;
	property TailPitch : tailPitch;
	
	string smokeColor;
	property MuzzleSmokeColor : smokeColor;
	
	class<PB_WeaponBase> UpgradedWeapon;
	Property Upgrade : UpgradedWeapon;
	
	class<PB_WeaponBase> DowngradeWeapon;
	Property Downgrade : DowngradeWeapon;
	Property UnUpgraded : DowngradeWeapon;
	
	int ReserveToMagAmmoFactor;
	property ReserveToMagAmmoFactor:ReserveToMagAmmoFactor;
	
	//[AD] Use when all weapons converted to ZS
	/*
	int cmag1,cmag2,pmag;
	property MagSize : pmag;
	*/
	class<Ammo> AmmoTypeLeft;
	Ammo AmmoLeft;
	Property AmmoTypeLeft: AmmoTypeLeft;
	
	enum PB_VisorBlood {
		REDBLOODVISOR,
		GREENBLOODVISOR,
		BLUEBLOODVISOR,
		ERRORBLOODVISOR
	}
	
	enum PB_OverlayLayers {
		PSP_LEDGEGRAB					= 1000,
		PSP_SWITCH_EQUIPMENT_LAYER 		= 834,
		PSP_LEFTGUN						= 10,
		PSP_RIGHTGUN					= 11,
		FLASH_LAYER						= -3,
		LEFT_FLASH_LAYER				= -4,
		RIGHT_FLASH_LAYER				= -5,
		PSP_REVENANTLAUNCHERLAYER		= -85,
		PSP_LEECHBEAMLAYER				= -86,
		PSP_MELEEEQHANDLER				= -777,
		PSP_QUICKMELEEBLOOD				= -997,
		PSP_QUICKMELEE					= -998,
		PSP_DOKICK						= -999,
		PSP_FIRSTPERSONLEGS				= -1000
	}

	enum PB_GrabbedBarrel {
		GRABBED_NORMAL_BARREL,
		GRABBED_FLAME_BARREL,
		GRABBED_ICE_BARREL
	}

	enum PB_WeaponReadyFlags {
		PB_NOWEAPONSPECIAL				= 1 << 0,
		PB_NOUNLOAD						= 1 << 1,
		PB_FORCERELOAD					= 1 << 2
	}

	Default
	{
		Weapon.BobRangeX 0.3;
		Weapon.BobRangeY 0.5;
		Weapon.BobSpeed 2.4;
		Weapon.BobStyle "InverseSmooth";
		Weapon.AmmoUse 0;
		Weapon.AmmoGive 0;
		PB_WeaponBase.UsesWheel false;
		PB_WeaponBase.WheelInfo "";
		PB_WeaponBase.TailSoundVolume 0.8;
		PB_WeaponBase.MuzzleSmokeColor "FFFFFF";
		PB_WeaponBase.ReserveToMagAmmoFactor 1;
		PB_WeaponBase.HUDFormatPrimary true, "%u", 1;
		PB_WeaponBase.HUDFormatSecondary true, "%u", 1;
		PB_WeaponBase.HUDFormatLeft true, "%u", 1;
		//Weapon.WeaponScaleX 1.2;
		+DONTGIB
		+FLOORCLIP
		+WEAPON.NOALERT
		+WEAPON.NOAUTOAIM
		+WEAPON.NOAUTOFIRE
		+WEAPON.AMMO_OPTIONAL
	}
	
	States
	{
		Select:
		TNT1 A 1 A_Raise;
		Wait;

		Fire:
		Ready:
		SelectAnimation:
			Goto GoingToReady;
		Deselect:
			TNT1 A 1 A_Lower;
			Wait;
			
			HelmetAnimation:
			TNT1 A 1 {
				A_GiveInventory("PB_NoEffectInvul",1);
				A_GiveInventory("sae_extcam", 1);
				A_GiveInventory("sae_deathcam", 1);
				A_GiveInventory("DoingHelmetAnim", 1);
				A_SetCrosshair(5);//A_SetBlend("00 00 00", 1, 35, "00 00 00", 0);
				Return ResolveState(null);
			}
			TNT1 A 34 {
				A_StartSound("IronSights",CHAN_AUTO);
				Return ResolveState(null);
			}
			H3L1 ABCDE 1 A_SetRoll(roll+10, SPF_INTERPOLATE);
			TNT1 A 0 A_StartSound("RSUP1",CHAN_AUTO);
			H3L1 FGHIJK 1 A_SetRoll(roll+5, SPF_INTERPOLATE);
			H3L1 LMNOP 1 A_SetRoll(roll-3, SPF_INTERPOLATE);
			//add sound for hand grabbing other side
			H3L1 QRSTUVWXYZ 1;
			H3L2 ABCD 1;
			H3L2 E 1 A_StartSound("IronSights",CHAN_AUTO);
			H3L2 FGHIJKLMNOPQRSTUVWXYZ 1 A_SetRoll(roll-3, SPF_INTERPOLATE);
			H3L3 ABCD 1;
			H3L3 E 1 A_StartSound("IronSights",CHAN_AUTO);
			H3L3 FGHIJ 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			H3L3 JKLMN 1 A_SetRoll(roll+1.5, SPF_INTERPOLATE);
			H3L3 OPQRS 1 A_SetRoll(roll+3, SPF_INTERPOLATE);
			H3L3 TUVWXYZ 1 A_SetRoll(roll+3, SPF_INTERPOLATE);
			H3L4 ABC 1 A_SetRoll(roll+3, SPF_INTERPOLATE);
			H3L4 DEFGH 1 A_SetRoll(roll+3.5, SPF_INTERPOLATE);
			H3L4 I 1
			{
				A_StartSound("helmet/swipe");
				A_SetRoll(roll+2.5, SPF_INTERPOLATE);
			}
			H3L4 JKLMNOP 1 A_SetRoll(roll+2.5, SPF_INTERPOLATE);
			H3L4 Q 1
			{
				A_StartSound("helmet/swipe");
				A_SetRoll(roll+2, SPF_INTERPOLATE);
			}
			H3L4 RSTUVWXYZ 1 A_SetRoll(roll+2, SPF_INTERPOLATE);
			H3L5 ABC 1 A_SetRoll(roll+3, SPF_INTERPOLATE);
			H3L5 DEF 1 A_SetRoll(roll+4, SPF_INTERPOLATE);
			H3L5 GH 1 A_SetRoll(roll+5, SPF_INTERPOLATE);
			H3L5 I 1
			{
				A_StartSound("RSUP2",CHAN_AUTO);
				A_SetRoll(roll+5, SPF_INTERPOLATE);
			}
			H3L5 JKL 1 A_SetRoll(roll+2.5, SPF_INTERPOLATE);
			H3L5 MNO 1 A_SetRoll(roll+1, SPF_INTERPOLATE);
			H3L5 P 1 A_StartSound("marine/superfist6",CHAN_AUTO);
			H3L5 QRS 1;
			H3L5 T 8;
			H3L5 UVXYZ 1;
			TNT1 A 0 A_SetBlend("00 00 00", 0, 8, "00 00 00", 1);
			H3L6 A 1
			{
				A_StartSound("HLMTPUT",CHAN_AUTO);
				A_SetRoll(roll+(frandom(-2,2)), SPF_INTERPOLATE);
			}
			H3L6 BCDEF 1 A_SetRoll(roll+(frandom(-2,2)), SPF_INTERPOLATE);
			H3L6 G 1
			{
				A_StartSound("HLMTBEP",CHAN_AUTO);
				A_SetRoll(roll+(frandom(-2,2)), SPF_INTERPOLATE);
			}
			H3L6 H 8 A_SetBlend("00 00 00", 1, 10, "51 92 99", 1);
			TNT1 A 1 A_StartSound("HLMTBPP",CHAN_AUTO);
			TNT1 A 20 A_SetBlend("51 92 99", 1, 20, "51 92 99", 0);
			TNT1 A 0
			{
				A_TakeInventory("PB_NoEffectInvul",1);
				A_TakeInventory("sae_extcam", 1);
				A_TakeInventory("sae_deathcam", 1);
				A_TakeInventory("CantDoAction",1);
				A_TakeInventory("DoingHelmetAnim", 1);
				A_GiveInventory("IntroductionSequence");
			}
			TNT1 A 0 {
				A_WeaponOffset(0,32);
				return PB_RespectIfNeeded();
			}
			Goto Ready3;
		WeaponRespect:
			TNT1 A 0 A_Jump(256, "SelectAnimation");
		Ready3:
			TNT1 A 1 A_Jump(256, "Ready3");
			Loop;	
		
		Flash:
			TNT1 A 1;
			Stop;
			
		StainedLedgeClimb:
			3L1M A 0 A_JumpIfInventory("PowerGreenBloodOnVisor",1,4);
			2L1M A 0 A_JumpIfInventory("PowerBlueBloodOnVisor",1,3);
			1L1M A 0 A_JumpIfInventory("PowerBloodOnVisor",1,2);
		LedgeClimb:
			CL1M A 0;
			"####" A 0 {
				A_StopSound(1);
				A_StopSound(5);
				A_StopSound(6);
				A_StopSound(7);
				PB_SetZoom(false);
				A_TakeInventory("CantDoAction",1);
				A_TakeInventory("PB_NoEffectInvul",1);
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, false);
				A_ClearOverlays(-80, 80);
				A_ClearReFire();
				A_Stop();
				A_Overlay(PSP_LEDGEGRAB,"LedgeGrabFlash");
				A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
				SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
				PB_SetReloading(false);
				A_StartSound("ledgeclimb",5);
			}
			"####" ABC 1 {
				let plr = PlayerPawnBase(self);
				
				if(Pos.Z < (plr.LedgeHeight - Height * 0.78f))
				{
					A_SetPitch(pitch-pitch/2, SPF_INTERPOLATE);
					Vel = Vel.Length() ? (0, 0, plr.velz) : (0, 0, 0);
					//plr.velz--;
				}
				else if(Pos.Z < (plr.LedgeHeight - Height * 0.76f))
				{
					LedgeReach(0.751);
					return ResolveState("LedgeReach");
				}
				return ResolveState(null);
			}
		LedgeReach:
			"####" A 0 A_ClearOverlays(-80,80);
			"####" A 0 A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, false);
			"####" D 1 {
				let plr = PlayerPawnBase(self);
				//if(Pos.Z >= (plr.LedgeHeight - Height * 0.78f) && Pos.Z < (plr.LedgeHeight - Height * 0.76f))
				if(Pos.Z >= (plr.LedgeHeight - Height * 0.78f))
				{
					A_SetPitch(pitch-pitch/2, SPF_INTERPOLATE);
					SetInventory("Grabbing_A_Ledge",1); //SetInventory fixes the looping ledge grab bug when sv_unlimited_pickup 1 is on
					LedgeReach(0.751);
				}
				else if(Pos.Z < (plr.LedgeHeight - Height * 0.78f))
				{
					Vel = Vel.Length() ? (0, 0, plr.velz) : (0, 0, 0);
				}
			}
			"####" A 0 A_JumpIf(WaterLevel <= 2, 1);
			Goto FinishClimb+11;
			"####" A 0 A_JumpIf(CountInv("Grabbing_A_Ledge")==1, 1);
			Goto LedgeReach;
			
			"####" E 1 {
				A_ClearOverlays(-80,80);
				let plr = PlayerPawnBase(self);
				plr.velz = 3.6;
				A_SetPitch(0, SPF_INTERPOLATE);
				LedgeReach(0.751);
				A_StopSound(CHAN_WEAPON);
				plr.LedgeAngle = Angle;
				plr.LedgeCheck = False;
				plr.LedgeGrabbed = True;
			}
			"####" F 1 {
				A_SetPitch(pitch-0.5, SPF_INTERPOLATE);
				Vel = Vel.Length() ? (0, 0, 0.62) : (0, 0, 0);
			}
			"####" G 1 {
				let plr = PlayerPawnBase(self);
				A_SetPitch(pitch+3, SPF_INTERPOLATE);
				Vel = Vel.Length() ? (0, 0, plr.velz) : (0, 0, 0);
			}
			"####" HI 1 {
				let plr = PlayerPawnBase(self);
				A_SetPitch(pitch+4, SPF_INTERPOLATE);
				plr.velz += 0.5;
				
				Vel = Vel.Length() ? (0, 0, plr.velz) : (0, 0, 0);
			}
		FinishClimb:
			3L1M A 0 A_JumpIfInventory("PowerGreenBloodOnVisor",1,4);
			2L1M A 0 A_JumpIfInventory("PowerBlueBloodOnVisor",1,3);
			1L1M A 0 A_JumpIfInventory("PowerBloodOnVisor",1,2);
			CL1M A 0;
			"####" A 0 {
				A_ClearOverlays(-80,80);
				A_OverlayFlags(PSP_WEAPON,PSPF_PLAYERTRANSLATED, false);				
				A_Overlay(PSP_LEDGEGRAB,"LedgeGrabFlash");
			}
			"####" JK 1 {
				let plr = PlayerPawnBase(self);
				plr.velz = 3.6;
				A_SetPitch(pitch-3, SPF_INTERPOLATE);
				Vel = Vel.Length() ? (0, 0, plr.velz) : (0, 0, 0);
			}
			"####" LM 1 A_SetPitch(pitch-2, SPF_INTERPOLATE);
			TNT1 AA 1 {
				A_SetPitch(pitch-pitch/2, SPF_INTERPOLATE);
				//A_WeaponReady();
			}
			// New, and to prevent an issue with melee not working after climbing during it's animation
			TNT1 A 0 {
				PB_SetUsingKick(false);
				PB_SetUsingMelee(false);
				PB_SetUsingEquipment(false);
				PB_SetExecutingEnemy(false);
				A_SetPitch(0, SPF_INTERPOLATE);
				SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
				A_SetInventory("sae_extcam", 0);
				A_SetInventory("sae_deathcam", 0);
			 	SetInventory("Grabbing_A_Ledge", 0);
				A_LegOverlay(PSP_FIRSTPERSONLEGS, "FirstPersonLegsStand");
			}
			TNT1 A 0 A_Jump(256,"SelectAnimation");
			Goto Ready3;

			Melee_Equipment_Handler_Overlay:
				TNT1 A 1 {
					if( (!((PressingFire() || JustPressed(BT_ATTACK)) || (ResolveState("AltFire") && (!PB_GetZoom() && (PressingAltFire() || JustPressed(BT_ALTATTACK)))))) && EQ_GetEquipment() != REV_GUN)
					{
						if(JustPressed(BT_USER1) && !PB_usingMelee() && !PB_executingEnemy() && !PB_usingEquipment() && !CheckInventory("CantDoAction",1)) 
						{
							if(CheckInventory("DoingHelmetAnim",1))
							{
								A_TakeInventory("PB_NoEffectInvul",1);
								A_TakeInventory("sae_extcam", 1);
								A_TakeInventory("sae_deathcam", 1);
								A_TakeInventory("CantDoAction",1);
								A_TakeInventory("DoingHelmetAnim", 1);
							}
							
							if(!PB_usingKick())
							{
								PB_SetUsingEquipment(true);
								EQ_UseEquipment(); // This is inside BaseWeapon_Equipment.zsc
							}
						}
						
						if(JustPressed(BT_USER2) && !PB_usingMelee() && !PB_executingEnemy() && !PB_usingEquipment() && !CheckInventory("CantDoAction",1)) 
						{
							if(CheckInventory("DoingHelmetAnim",1))
							{
								A_TakeInventory("PB_NoEffectInvul",1);
								A_TakeInventory("sae_extcam", 1);
								A_TakeInventory("sae_deathcam", 1);
								A_TakeInventory("CantDoAction",1);
								A_TakeInventory("DoingHelmetAnim", 1);
							}
							 
							{
								PB_SetUsingMelee(true);
								A_Overlay(PSP_QUICKMELEE, "QuickMelee");
							}
						}
					}
					else{
						if(JustPressed(BT_USER1) && !PB_executingEnemy() && !PB_usingMelee() ) //&& !CheckInventory("CantDoAction",1)
						{
							if(CheckInventory("DoingHelmetAnim",1))
							{
								A_TakeInventory("PB_NoEffectInvul",1);
								A_TakeInventory("sae_extcam", 1);
								A_TakeInventory("sae_deathcam", 1);
								A_TakeInventory("CantDoAction",1);
								A_TakeInventory("DoingHelmetAnim", 1);
							}
							if(EQ_GetEquipment() == REV_GUN && !player.FindPSprite(PSP_REVENANTLAUNCHERLAYER)){
								A_OverlayOffset(PSP_REVENANTLAUNCHERLAYER, 0, 32);
								A_Overlay(PSP_REVENANTLAUNCHERLAYER, "FireRevGun");
								A_OverlayPivotAlign(PSP_REVENANTLAUNCHERLAYER,PSPA_CENTER,PSPA_CENTER);
								A_OverlayFlags(PSP_REVENANTLAUNCHERLAYER,PSPF_RENDERSTYLE,true);
								A_OverlayOffset(PSP_REVENANTLAUNCHERLAYER, 0, 32);
							}
						}
						if(JustPressed(BT_USER2) && !PB_usingMelee() && !PB_executingEnemy() && !PB_usingEquipment() && !PB_GetZoom() && !CheckInventory("CantDoAction",1) && (!((PressingFire() || JustPressed(BT_ATTACK)) || (ResolveState("AltFire") && (PressingAltFire() || JustPressed(BT_ALTATTACK))))) ) 
						{
							if(CheckInventory("DoingHelmetAnim",1))
							{
								A_TakeInventory("PB_NoEffectInvul",1);
								A_TakeInventory("sae_extcam", 1);
								A_TakeInventory("sae_deathcam", 1);
								A_TakeInventory("CantDoAction",1);
								A_TakeInventory("DoingHelmetAnim", 1);
							}
							 
							{
								PB_SetUsingMelee(true);
								A_Overlay(PSP_QUICKMELEE, "QuickMelee");
								A_OverlayOffset(PSP_QUICKMELEE, 0, 32);
							}
						}
					}
					if(!PB_GetZoom() 
						&& EQ_GetEquipment() == REV_GUN 
						&& (PressingUser1() || player.FindPSprite(PSP_REVENANTLAUNCHERLAYER)) 
					)
						A_OverlayScale(PSP_REVENANTLAUNCHERLAYER,1.3398);
					else
					{
						A_OverlayScale(PSP_REVENANTLAUNCHERLAYER,1.0);
						A_OverlayRenderstyle(PSP_REVENANTLAUNCHERLAYER,STYLE_Normal);
					}
				}
				Loop;
		// [Beef] this is actually unused since I've moved it to DoEffect()
		// but I'll keep this here
		// KickHandler_Overlay:
		// 	TNT1 A 1 {
		// 		if(CountInv("ResetKick")>=1)
		// 		{
		// 			A_TakeInventory("ResetKick", 1);
		// 			PB_SetUsingKick(false);
		// 			A_TakeInventory("Kicking", 1);
		// 		}
		// 		if(CountInv("Grabbing_A_Ledge")==0 && CountInv("Kicking")==0 && ((JustPressed(BT_USER4) || player.crouchdir == -1 && CountInv("CanSlideKick") == 1) && !PB_usingKick() && !PB_executingEnemy() && PB_MeleeAttackKickCheck()))
		// 		{
		// 			PB_SetUsingKick(true);
		// 			A_LegOverlay(PSP_DOKICK, "DoKick");
		// 			A_OverlayFlags(PSP_DOKICK,PSPF_ADDWEAPON|PSPF_ADDBOB, False);
		// 			A_OverlayFlags(PSP_DOKICK,PSPF_PLAYERTRANSLATED, true);
		// 		}
		// 	}
		// 	Loop;
		// Initialize Weapon upon selection
		GoingToReady:
			TNT1 A 0 A_JumpIfInventory ("HasBarrel", 1, "ReadyBarrel");
			TNT1 A 0 A_JumpIfInventory ("HasFlameBarrel", 1, "ReadyFlameBarrel");
			TNT1 A 0 A_JumpIfInventory ("HasIceBarrel", 1, "ReadyIceBarrel");
		SelectingAnimation:
			TNT1 A 0 {
				A_TakeInventory("KeepLaserDeactivated",1);
				A_TakeInventory("DoGrenade",1);
				A_TakeInventory("IsRunning",1);
				A_TakeInventory("Reloading",1);
				A_LegOverlay(PSP_FIRSTPERSONLEGS, "FirstPersonLegsStand");
				A_ClearOverlays(PSP_DOKICK, PSP_DOKICK);
				A_SetInventory("Grabbing_A_Ledge",0);
				A_SetInventory("Kicking",0);
				// New 
				PB_SetUsingKick(false);
				PB_SetUsingMelee(false);
				PB_SetUsingEquipment(false);
				PB_SetExecutingEnemy(false);
				A_ClearReFire(); //Prevents altfire hold glitches
				
			}
			TNT1 A 0 A_JumpIf(PB_GetZoom(),"Ready2");
			TNT1 A 0 A_Jump(256,"Ready3");
			TNT1 A 0 A_Jump(256,"Ready");
			Wait;
		SelectFirstPersonLegs:
			TNT1 A 0 {
				A_StopSound(1);
				A_StopSound(CHAN_VOICE);
				A_StopSound(5);
				A_StopSound(6);
				A_StopSound(7);
				A_StopSOund(CHAN_AUTO);
				A_TakeInventory("CantWeaponSpecial",1); //Fixes bug with Weapon Special Key no longer working when changing SGL grenade type or RL missile mode
				A_TakeInventory("MG42Selected",1); //Take this token on every weapon that's not the MG42.
				A_SetInventory("Grabbing_A_Ledge", 0); //Fixed bug where movement is locked when vaulting after entering a level
				A_Takeinventory("RandomHeadExploder",1);
				A_TakeInventory("DualFireReload",2);
				A_Overlay(PSP_MELEEEQHANDLER, "Melee_Equipment_Handler_Overlay");
				A_LegOverlay(PSP_FIRSTPERSONLEGS, "FirstPersonLegsStand");
				A_ClearOverlays(PSP_DOKICK, PSP_DOKICK);
				PB_SetUsingKick(false);
				PB_SetZoom(false);
				A_SetInventory("Kicking",0);
			}
			TNT1 A 0 A_Jump(256, "SelectContinue");
			Loop;
		TryToSelectDrum:
			TNT1 AAAA 1 A_Jump(256, "Ready3");
			TNT1 AAAA 1 A_Jump(256, "BeltReady");
			Loop;
		GoingToReady2:
			TNT1 A 0 {
				A_TakeInventory("KeepLaserDeactivated",1);
				A_TakeInventory("ToggleEquipment",1);
				PB_SetUsingMelee(false);
				PB_SetUsingEquipment(false);
				A_LegOverlay(PSP_FIRSTPERSONLEGS, "FirstPersonLegsStand");
				A_ClearReFire();
			}
			TNT1 A 0 A_JumpIfInventory("SawSelected", 1, "Reselect");
			TNT1 AAAA 0 A_Jump(256, "SelectAnimation");
			TNT1 AAAA 1 A_Jump(256, "Ready");
			Loop;
			
		Steady:
			TNT1 A 1 {
				// New 
				PB_SetUsingKick(false);
				PB_SetUsingMelee(false);
				PB_SetUsingEquipment(false);
				PB_SetExecutingEnemy(false);
			}
			Goto GoingToReady;
		FirstPersonLegsKickRight:
			STAN A 0;
			"####" A 0 A_GiveInventory("KeepLaserDeactivated",1);
			"####" A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsHideAir");
			"####" A 0 A_JumpIf(Height < 54, "FirstPersonLegsHide");
			"####" A 0 A_JumpIfInventory("FPSLegChecker", 1, 2);
			"####" O 1
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
			"####" P 1
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
		FirstPersonLegsKickLeft:
			STAL A 0;
			"####" A 0 A_GiveInventory("KeepLaserDeactivated",1);
			"####" A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsHideAir");
			"####" A 0 A_JumpIf(Height < 54, "FirstPersonLegsHide");
			"####" A 0 A_JumpIfInventory("FPSLegChecker", 1, 2);
			"####" P 1
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
			"####" O 1
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
		FirstPersonLegsHide:
			"####" Q 1 
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
		FirstPersonLegsHideAir:
			"####" R 1 
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
		FirstPersonLegsStand:
			TNT1 A 0 A_JumpIf(vel.x > 0.8 || vel.x < -0.8 || vel.y > 0.8 || vel.y < -0.8, "FirstPersonLegsWalk1");
			TNT1 A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			TNT1 A 0 A_JumpIf(Height < 54, "FirstPersonLegsCrouch");
			TNT1 A 0 A_JumpIfInventory("FPSLegChecker", 1, 2);
			STAN A 1 
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
			TNT1 A 0 A_JumpIf(Height < 54, "FirstPersonLegsCrouch");
			TNT1 A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			STAN M 1 
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
		FirstPersonLegsCrouch:
			TNT1 A 0 A_StartSound("IronSights", 0); //Sound when player crouches
		FirstPersonLegsCrouchContinue:
			TNT1 A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			TNT1 A 0 A_JumpIf(vel.x > 0.8 || vel.x < -0.8 || vel.y > 0.8 || vel.y < -0.8, "FirstPersonLegsWalk1");
			TNT1 A 0 A_JumpIf(Height > 54, "FirstPersonLegsStand");
			STAN N 1 
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Loop;
		FirstPersonLegsWalk1:
			TNT1 A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			TNT1 A 0 A_JumpIfInventory("FPSLegChecker", 1, "FirstPersonLegsWalk2");
			TNT1 A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			TNT1 A 0 A_GiveInventory("FPSLegChecker",1);
			STAN BCCDDEEFF 1
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
				return A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			}
			Goto FirstPersonLegsStand;
		FirstPersonLegsWalk2:
			TNT1 A 0 A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			TNT1 A 0 A_TakeInventory("FPSLegChecker",1);
			STAN GHHIIJJKLL 1 
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
				return A_JumpIf(vel.z != 0, "FirstPersonLegsJump");
			}
			Goto FirstPersonLegsStand;
		FirstPersonLegsJump:
			STAN I 5
			{
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_ADDWEAPON|PSPF_ADDBOB, False);
				A_OverlayFlags(PSP_FIRSTPERSONLEGS, PSPF_PLAYERTRANSLATED, True);
				A_OverlayOffset(PSP_FIRSTPERSONLEGS, 0, (-pitch*2)+230,WOF_INTERPOLATE);
				if(PB_executingEnemy() || CountInv("Grabbing_A_Ledge") > 0)
					A_SetOverlaySprite(PSP_FIRSTPERSONLEGS, "TNT1");
			}
			Goto FirstPersonLegsStand;


		Steady:
			Goto GoingToReady;

		// [Beef] so addon makers can play their custom animations using CustomInventory
		EmptyLayer:
			TNT1 A 1 A_JumpIf(!invoker.stayInEmptyLayer,"GoingToReady2");
			Loop;
	}
}

class PB_Weapon : PB_WeaponBase {} //This is just a dummy class for inheriting reasons

class PB_UpgradeItem : CustomInventory
{
	Default
	{+DONTGIB;}
	action void A_SetSpawnSprite(String str)
	{
		sprite = GetSpriteIndex(str);
	}
	
	action void A_SetWeaponTag(name target, string newTag)
	{
		let weap = FindInventory(target);
		if(weap) {
			weap.SetTag(newTag);
		}
	}
}

Class PB_WeaponAmmo : Ammo{
	Default{
		Inventory.Amount 0;
		Ammo.BackpackAmount 0;
		+INVENTORY.UNDROPPABLE
		+INVENTORY.UNTOSSABLE
		+INVENTORY.IGNORESKILL
	}
	override class<Ammo> GetParentAmmo(){
		class<Object> type = GetClass();
		while(type.GetParentClass()!= "PB_WeaponAmmo"&&type.GetParentClass()!=null) type = type.GetParentClass();
		return(class<Ammo>)(type);
	}
}

class PB_Token : Inventory abstract {
	Default {
		Inventory.MaxAmount 1;
	}
}