// [Beef] okay so I've reworked the equipment system from using overlays and states to just the DoEffect()
// Inside DoEffect() the equipment switch happens and it looks for the selectedEquipment variable inside PlayerPawn.zc
// that way the equipment will be consistent across weapons
// the actual equipment use still uses an empty overlay inside BaseWeapon.zc but it does call the EQ_UseEquipment() here

// Big thanks to Pope (ThePopeOfDope) for some the switch equipment animations since I took them from his Project Survival 

// TODO: Move the whole equipment system to a CustomInventory to reduce bloat in the BaseWeapon,
// this way we wont need the variable in PlayerPawn.zc
// either by making an eventhandler that works as an interface between the weapon and the CustomInventory or just by getting a pointer to it 

enum PB_Equipments {
	EQ_ERROR = -1,
	FRAG_GRENADE, //This is the default
	PROX_MINE,
	STUN_GRENADE,
	LEECH,
	REV_GUN
}

class PB_RevLauncherFireCount : Inventory{Default{Inventory.MaxAmount 3;}}
extend class PB_WeaponBase
{
//////////////////////////// EQUIPMENT FUNCTIONS ////////////////////////////////////////////////////////////////////////////////////
	action void EQ_SetEquipment(PB_Equipments set)
	{
		let pbplr = PB_PlayerPrawn(invoker.owner);
		if(pbplr)
		{
			pbplr.selectedEquipment = set;
		}
	}

	action int EQ_GetEquipment()
	{
		let pbplr = PB_PlayerPrawn(invoker.owner);
		if(pbplr)
		{
			return pbplr.selectedEquipment;
		}
		return EQ_ERROR;
	}

	action void EQ_UseEquipment()
	{
		// Check token or if the player is dead
		if(findinventory("CantDoAction") || health <= 0)
			A_Overlay(PSP_WEAPON, "FailOverlay");

		// Setup
		A_ClearOverlays(-80,80); // What even is in this range?
		A_TakeInventory("RailgunInfrared", 1);
		A_StopSound(CHAN_WEAPON);
		A_StopSound(CHAN_VOICE);
		A_StopSound(CHAN_6);
		A_StopSound(CHAN_7);
		A_TakeInventory("UseEquipment", 1);
			
		// Get variables
		int mode = EQ_GetEquipment();
		int grabbedBarrel = isHoldingBarrel();
		int amount;
		name itemType;
		string failMsg;
		StateLabel st;
		
		// Check barrels
		if(grabbedBarrel)
		{
			switch(grabbedBarrel)
			{
				case GRABBED_NORMAL_BARREL: st = "IdleBarrel"; 		break;
				case GRABBED_FLAME_BARREL: 	st = "IdleFlameBarrel"; break;
				case GRABBED_ICE_BARREL:	st = "IdleIceBarrel"; 	break;
			}
		}
		
		// Actual equipment logic
		switch(mode)
		{
			case FRAG_GRENADE: 	
				st 			= "ThrowGrenade"; 
				itemType 	= "PB_GrenadeAmmo";
				amount 		= 1;
				failMsg 	= "$PB_NO_FRAG";
				break;

			case PROX_MINE: 	
				st 			= "ThrowMine";
				itemType 	= "PB_Dtech";
				amount 		= 1;
				failMsg 	= "$PB_NO_PROX";				 	 
				break;

			case STUN_GRENADE: 	
				st 			= "ThrowStun";
				itemType 	= "PB_StunGrenadeAmmo";
				amount 		= 1;
				failMsg 	= "$PB_NO_STUN";
				break;

			case LEECH: 		
				st 			= "ThrowLeech"; 
				itemType 	= "PB_Dtech";
				amount 		= 4;
				failMsg 	= "$PB_NO_LEECH";
				break;

		}
		if(PB_CheckEquipment(itemType,amount,failMsg))
			A_Overlay(PSP_WEAPON, st);
		else
			A_Overlay(PSP_WEAPON, "GoingToReady");
		A_OverlayOffset(PSP_WEAPON, 0, 32);
	}

	void EQ_SwitchEquipment()
	{
		owner.A_TakeInventory("ToggleEquipment", 1);

		int mode 	= EQ_GetEquipment();
		int tokens 	= EQ_GetTokens();

		if(mode == tokens)
		{
			owner.A_Print("$PB_ALREADYSELECTED");
			EQ_ClearGearboxTokens();
			return;
		}

		string showText;
		string playSound;
		Statelabel st;
		switch(tokens)
		{
			case FRAG_GRENADE: 	showText = "$PB_SELECT_FRAG";	playSound = "GRNPIN";			 st = "EQ_FragSwitch";   break;	
			case PROX_MINE: 	showText = "$PB_SELECT_PROX";	playSound = "GRNPIN";			 st = "EQ_ProxSwitch";   break;	
			case STUN_GRENADE:	showText = "$PB_SELECT_STUN";	playSound = "StunGrenadePickup"; st = "EQ_StunSwitch";   break;	
			case LEECH: 		showText = "$PB_SELECT_LEECH";	playSound = "SiphonGrowl";		 st = "EQ_LeechSwitch";  break;	
			case REV_GUN: 		showText = "$PB_SELECT_REVGUN";	playSound = "REVUP";			 st = "EQ_RevGunSwitch"; break;	
		}
		
		EQ_SetEquipment(tokens);
		owner.A_Print(showText); 
		owner.A_StartSound(playSound, 3);
		EQ_ClearGearboxTokens();
		owner.player.SetPSprite(PSP_SWITCH_EQUIPMENT_LAYER,resolvestate(st));
		owner.player.SetPSprite(PSP_WEAPON,owner.player.readyweapon.resolvestate("FlashPunching"));
	}

	void EQ_ClearGearboxTokens()
	{
		owner.A_SetInventory("WW_FragGrenadeSelected",0);
		owner.A_SetInventory("WW_ProximityMineSelected",0);
		owner.A_SetInventory("WW_StunGrenadeSelected",0);
		owner.A_SetInventory("WW_LeechSelected",0);
		owner.A_SetInventory("WW_RevGunSelected",0);
	}
	
	// Convert the tokens into an int for easier use
	int EQ_GetTokens()
	{
		if(owner.FindInventory("WW_FragGrenadeSelected")) 
			return FRAG_GRENADE;
		else if(owner.FindInventory("WW_ProximityMineSelected"))
			return PROX_MINE;
		else if(owner.FindInventory("WW_StunGrenadeSelected"))
			return STUN_GRENADE;
		else if(owner.FindInventory("WW_LeechSelected"))
			return LEECH;
		else if(owner.FindInventory("WW_RevGunSelected"))
			return REV_GUN;
		else
			return EQ_ERROR; // If it returns this then something is catastrophically wrong lol
	}

	// Check if the player has enough ammo for the equipment
	action bool PB_CheckEquipment(class<Inventory> itemType, int amount, string failMsg)
	{
		A_StopSound(6);
		A_StopSound(CHAN_VOICE);

		A_TakeInventory("UseEquipment", 1);
		PB_SetReloading(false);

		Inventory item = FindInventory(itemType);
		if (!item || item.Amount < amount)
		{
			A_Print(failMsg);
			return false;
		}
		return true;
	}

//////////////////////////// STATES ////////////////////////////////////////////////////////////////////////////////////
	States
	{
//////////////////////////// EQUIPMENT ANIMATIONS ////////////////////////////////////////////////////////////////////////////////////
//////////////////////////// FRAG GRENADE ////////////////////////////////////////////////////////////////////////////////////
		ThrowGrenade:
			TNT1 A 0 A_Giveinventory("PlayerIsThrowingAGrenade",1);
			HNDF ABCDE 1 A_SetRoll(roll+2.0, SPF_INTERPOLATE);
			HNDF FGHI 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_StartSound("OPNGRN",0);
			HNDF JKLMNOPQR 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_JumpIfInventory("UseEquipment", 1, "TossGrenade");
			TNT1 A 1 A_SetRoll(roll-18.0);
			HND1 I 1 A_StartSound("THRGRN",0);
			HND1 J 1 {
				A_FireProjectile("PB_ThrownGrenade",0,0,0,0,0,0);
				A_TakeInventory("PB_GrenadeAmmo", 1, TIF_NOTAKEINFINITE);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
			}
			HND1 KLMNOPQ 1 A_SetRoll(roll-5.0);
			TNT1 A 0 {
				A_SetRoll(0, SPF_INTERPOLATE);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		TossGrenade:
			TNT1 A 1;
			HND1 RSTU 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_StartSound("THRGRN", 1);
				A_TakeInventory("PB_GrenadeAmmo", 1, TIF_NOTAKEINFINITE);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
				A_FireProjectile("ThrownGrenade15", 0,0,0,-2,0,3);
			}
			HND1 VWXY 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_SetRoll(0);
				A_TakeInventory("PB_LockScreenTilt",1);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;

		EQ_FragSwitch:
			EQFR MLKJAAAAAAJKLM 1;
			Stop;

//////////////////////////// PROXIMITY MINE ////////////////////////////////////////////////////////////////////////////////////
		ThrowMine:
			XPFF FEDCBA 1;
			XPFS B 4 A_StartSound("weapons/pbarm", 2);
			XHFF A 0 {
				A_StartSound("MINE002", 3);
				A_ThrowGrenade("PB_ThrownProxMine",4,11,1,0);
				A_TakeInventory("PB_ProxMineAmmo", 1, TIF_NOTAKEINFINITE);
			}
			XHFF MNOPQRSTUVWXYZ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;

		EQ_ProxSwitch:
			XPFB ABCDEEEEEEEDCBA 1;
			Stop;

//////////////////////////// STUN GRENADE ////////////////////////////////////////////////////////////////////////////////////
		ThrowStun:
			STNG BCDEF 1;
			STNG F 1 Offset(-2,34);
			TNT1 A 0 A_StartSound("StunGrenadeArm", 2);
			STNG GIJJJIHGKLMNOP 1;
			HND1 I 1 A_StartSound("THRGRN", 1);
			TNT1 A 0 A_TakeInventory("PB_StunGrenadeAmmo", 1, TIF_NOTAKEINFINITE);
			HND1 J 1 A_FireProjectile("PB_ThrownStunGrenade",0,0,0,0,0,0);
			HND1 KLMNOPQ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;

		EQ_StunSwitch:
			SHIG QRSTUVVVVUTSRQ 1;
			Stop;

//////////////////////////// LEECH ////////////////////////////////////////////////////////////////////////////////////
		LeechBeam:
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			Loop;
		ThrowLeech:
			TNT1 A 1 A_StartSound("SiphonActive", 3);
			SYNP KLMNO 1 A_WeaponOffset(0,32);
			TNT1 A 0 {
				A_StopSound(3);
				A_Overlay(PSP_LEECHBEAMLAYER, "LeechBeam");
			}
		HoldLeech:
			SYNP ABCDEF 2 {
				A_StartSound("SiphonHold",3,CHANF_LOOPING);
				A_FireBullets(0, 0, -1, 3, "SiphonPuff", FBF_NORANDOM|FBF_NOFLASH);
				A_TakeInventory("PB_Dtech", 4, TIF_NOTAKEINFINITE);
			}
			TNT1 A 0 A_JumpIf(CountInv("PB_Dtech") > 4 && PressingUser1(), "HoldLeech");
			TNT1 A 0 {
				A_StopSound(3);
				A_ClearOverlays(PSP_LEECHBEAMLAYER,PSP_LEECHBEAMLAYER);
				if(CountInv("PB_Dtech") < 4 && PressingUser1()) {
					A_Print("Insufficient Demon Energy");
				}
			}
			SYNP ONMLK 1;
			TNT1 A 0 {
				A_WeaponOffset(0,32);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;

		EQ_LeechSwitch:
			SYNP KLMN 1;
			SYNP GHIJ 4;
			SYNP NMLK 1;
			Stop;
		
//////////////////////////// REV GUN ////////////////////////////////////////////////////////////////////////////////////
		// This is an overlay
		FireRevGun:
			TNT1 A 0 A_TakeInventory("UseEquipment", 1);
			TNT1 A 0 A_JumpIfInventory("PB_QuickLauncherAmmo", 1, 2);
			TNT1 A 0 A_Print("$PB_NO_REVGUN");
			stop;
			TNT1 A 0 {A_StartSound("revup", CHAN_AUTO, CHANF_OVERLAP);}
			RVCA ABCDEFGHIJK 1;
			RVCF AB 1;
		FiringRevGun:
			TNT1 A 0 {if (player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))){return ResolveState("FireRevGunDeselect");} return ResolveState(null);}
			RVCF C 1 BRIGHT {
				A_AlertMonsters();
				A_TakeInventory("PB_QuickLauncherAmmo", 1, TIF_NOTAKEINFINITE);
				/*
				if(!FindInventory("PB_RevLauncherFireCount")){A_AlertMonsters();}
				if(CountInv("PB_RevLauncherFireCount")<3){A_GiveInventory("PB_RevLauncherFireCount",1);
				}else{A_TakeInventory("PB_QuickLauncherAmmo", 1);A_SetInventory("PB_RevLauncherFireCount",0);}
				*/
				A_FireProjectile("Alerter",0,0,-1,0);
				A_FireProjectile("DoomerRevenantSeeker3", random(4, -4), 0, -16, 8);
				A_StartSound("hellishmissle/fire",CHAN_AUTO, CHANF_OVERLAP, 0.5, pitch:frandom(0.95, 1.05));
				if(JustPressed(BT_USER1) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
					SetInventory("UseEquipment",1);
				}
			}
			RVCF D 1 BRIGHT {
				A_StartSound("hellishmissle/fire", CHAN_AUTO, CHANF_OVERLAP, 0.5, pitch:frandom(0.95, 1.05));
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_FireProjectile("DoomerRevenantSeeker2", random(4, -4), 0, 16, 8);
				if(JustPressed(BT_USER1) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
					SetInventory("UseEquipment",1);
				}
			}
			RVCF EFG 1 BRIGHT {
				if(player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))) {
					return ResolveState("FireRevGunDeselect");
				}
				if((JustPressed(BT_USER1) || FindInventory("UseEquipment")) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
					return ResolveState("FireRevGunFinish");
				}
				return ResolveState(null);
			}
			RVCF HI 1 {
				if(player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))) {
					return ResolveState("FireRevGunDeselect");
				}
				if((JustPressed(BT_USER1) || FindInventory("UseEquipment")) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
					return ResolveState("FireRevGunFinish");
				}
				return ResolveState(null);
			}
			TNT1 A 0 A_JumpIf(CountInv("PB_QuickLauncherAmmo") > 0 && (PressingUser1() || CVar.GetCVar("pb_toggle_launchers", player).GetBool()), "FiringRevGun");
			goto FireRevGunFinish;
		FireRevGunFinish:
			TNT1 A 0 {
				if(CountInv("PB_QuickLauncherAmmo") < 1 && (PressingUser1() || CVar.GetCVar("pb_toggle_launchers", player).GetBool() && !FindInventory("UseEquipment"))) {
					A_Print("No Quick Launcher Missiles Left");
				}
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			RVCF BA 1;
			RVCA K 1 A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
			RVCA JIHGFEDCB 1;
			RVCA A 1 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			stop;
		FireRevGunDeselect:
			RVCA H 1 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
			}
			RVCA FDCB 1;
			stop;
		
		EQ_RevGunSwitch:
			RVC1 DCBAAAAAAAABCD 1;
			Stop;
	}
}